#ifndef _IAiManager_H
#define _IAiManager_H

#include <Workphone/WorkphonePrerequisites.hpp>
#include <Workphone/Interface/Memory/ISharedObject.hpp>

namespace workphone
{

    /**
     * @class IAiManager
     * @brief Interface for managing AI operations, pathfinding, and response processing within the
     * Workphone system.
     *
     * This interface defines the contract for classes that manage the interaction with an AI subsystem,
     * including fetching paths and processing AI query responses.
     */
    class WPCore_API IAiManager : public ISharedObject
    {
    public:
        /**
         * @brief Virtual destructor.
         */
        ~IAiManager() override;

        /**
         * @brief Retrieves the pathfinder object managed by this manager.
         * @return A smart pointer to the underlying IPathfinder2 instance.
         */
        virtual SmartPtr<IPathfinder2> getPathfinder2() const = 0;

        /**
         * @brief Sets the pathfinder2 object for AI operations.
         * @param pathfinder The smart pointer to the IPathfinder2 object.
         */
        virtual void setPathfinder2( SmartPtr<IPathfinder2> pathfinder ) = 0;

        /**
         * @brief Queries the AI manager for a response based on a given prompt.
         * @param prompt The user prompt to be processed by the AI.
         * @return The textual response generated by the AI model.
         */
        virtual String query( const String &prompt ) const = 0;

        /**
         * @brief Processes a structured AI response and applies supported engine actions.
         *
         * Only explicitly allow-listed engine actions are accepted. Arbitrary code,
         * console commands, or file operations are never executed through this method.
         *
         * @param response JSON response containing an `actions` array to be evaluated.
         * @return True when at least one valid action was successfully applied to the system.
         */
        virtual bool processResponse( const String &response ) const = 0;

        WP_CLASS_REGISTER_DECL;
    };
}  // namespace workphone

#endif  // _IAiManager_H
