add_subdirectory(./WorkphoneAudio)
add_subdirectory(./WorkphoneCollision)
add_subdirectory(./WorkphoneCore)
add_subdirectory(./WorkphoneGraphics)
add_subdirectory(./WorkphoneNetwork)
add_subdirectory(./WorkphonePhysics)
add_subdirectory(./WorkphonePlatform)
add_subdirectory(./WorkphonePlatformApple)
add_subdirectory(./WorkphonePlatformDreamcast)
add_subdirectory(./WorkphonePlatformWin32)
add_subdirectory(./WorkphoneProcedural)
add_subdirectory(./WorkphoneRuntime)
add_subdirectory(./WorkphoneScript)
add_subdirectory(./WorkphoneVehicle)