foreach(required WP_LUAJIT_SOURCE WP_LUAJIT_BUILD_ROOT WP_LUAJIT_CONFIG WP_LUAJIT_VS)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
if(NOT WP_LUAJIT_CONFIG MATCHES "^[A-Za-z0-9_]+$")
    message(FATAL_ERROR "Invalid LuaJIT configuration")
endif()
file(REAL_PATH "${WP_LUAJIT_BUILD_ROOT}" build_root)
set(work "${build_root}/${WP_LUAJIT_CONFIG}")
file(MAKE_DIRECTORY "${work}")
file(COPY "${WP_LUAJIT_SOURCE}/src/" DESTINATION "${work}/src")
file(COPY "${WP_LUAJIT_SOURCE}/dynasm" DESTINATION "${work}")
file(COPY "${WP_LUAJIT_SOURCE}/.relver" DESTINATION "${work}")
file(REMOVE "${work}/src/lua51.lib" "${work}/src/luajit.exe")
set(crt "/MD")
if(WP_LUAJIT_CRT STREQUAL "MT")
    set(crt "/MT")
endif()
set(options "static")
if(WP_LUAJIT_CONFIG STREQUAL "Debug")
    string(APPEND crt "d")
    set(options "debug static")
endif()
file(TO_NATIVE_PATH "${WP_LUAJIT_VS}/Common7/Tools/VsDevCmd.bat" developer_command)
file(WRITE "${work}/build.cmd"
    "@echo off\r\ncall \"${developer_command}\" -arch=x64 -host_arch=x64 -no_logo\r\nif errorlevel 1 exit /b 1\r\nset CL=${crt}\r\ncd /d \"${work}/src\"\r\ncall msvcbuild.bat ${options}\r\nif not exist lua51.lib exit /b 1\r\nif not exist luajit.exe exit /b 1\r\n")
execute_process(COMMAND cmd /c "${work}/build.cmd" RESULT_VARIABLE status)
if(NOT status EQUAL 0 OR NOT EXISTS "${work}/src/lua51.lib" OR NOT EXISTS "${work}/src/luajit.exe")
    message(FATAL_ERROR "LuaJIT upstream build failed")
endif()
file(COPY "${work}/src/lua51.lib" "${work}/src/luajit.exe" DESTINATION "${work}")
# msvcbuild.bat may report success after a failed incremental build. Verify the VM.
execute_process(COMMAND "${work}/luajit.exe" -e "assert(jit and jit.version_num >= 20100)"
    RESULT_VARIABLE vm_status)
if(NOT vm_status EQUAL 0)
    message(FATAL_ERROR "The generated LuaJIT executable did not run")
endif()
