#ifndef CAircraftWing_h__
#define CAircraftWing_h__

#include "WPVehiclePhysics/WPVehiclePhysicsPrerequisites.hpp"
#include <Workphone/Interface/Vehicle/IAircraftWing.hpp>
#include "WPVehiclePhysics/CAircraftAttachment.hpp"
#include "WPVehiclePhysics/InputController.hpp"
#include "Workphone/Core/Array.hpp"
#include <Workphone/Core/FixedArray.hpp>
#include <Workphone/Core/Properties.hpp>
#include <Workphone/Math/Vector3.hpp>

namespace workphone::vehicle
{
    /** Class to calculate forces generated by a wing. */
    class WPVehiclePhysics_API CAircraftWing : public CAircraftAttachment<IAircraftWing>
    {
    public:
        static constexpr s32 m_maxSections = 10;

        /** Default constructor. Sets up default values. */
        CAircraftWing();
        ~CAircraftWing() override;

        void load(SmartPtr<ISharedObject> data) override;
        void load(void *pData) override;
        void unload(SmartPtr<ISharedObject> data) override;

        void update(const double &t, const double &dt) override;

        SmartPtr<IAircraftControlSurface> getAttachedControlSurface() const override;
        void setAttachedControlSurface(
            SmartPtr<IAircraftControlSurface> attachedControlSurface) override;

        SmartPtr<IAircraftPropWash> getAttachedPropWash() const override;
        void setAttachedPropWash(SmartPtr<IAircraftPropWash> attachedPropWash) override;

        bool isControlSurface() const override;
        void setControlSurface(bool bIsControlSurface) override;

        bool useCombinedControlSurface() const override;
        void setUserCombinedControlSurface(bool bUseCombinedControlSurface) override;

        void reset() override;

    private:
        void updateGeometry() override;

        real_Num calculateArea(const Vector3<real_Num> &pointA, const Vector3<real_Num> &pointB,
                               const Vector3<real_Num> &pointC, const Vector3<real_Num> &pointD);

        s32 getDebugId(s32 i) const;

        s32 getDebugId(s32 section, s32 index) const;

        void drawGizmos();

        Vector3<real_Num> calculateRelativeWind(s32 sectionIndex,
                                                const Vector3<real_Num> &aerodynamicCenter,
                                                const Vector3<real_Num> &wind);

        Vector3<real_Num> calculateRelativeWind2(s32 sectionIndex,
                                                 const Vector3<real_Num> &aerodynamicCenter,
                                                 const Vector3<real_Num> &wind);

        Vector3<real_Num> calculateRelativeWind3(s32 sectionIndex,
                                                 const Vector3<real_Num> &aerodynamicCenter,
                                                 const Vector3<real_Num> &wind);

        void calculateStallControl();
        void calculateForcesSimple(double fDT);
        void calculateForces(double t, double fDT);

        void updateForcesFast(double t, double fDT);

        void calculateAlphaDebug(double t, double dt);
        void calculateAlpha();
        void calculateAlphaReversed();

        void calculateArea();

        void calculateRelativeWindDebug(double dt);

        void calculateRelativeWind(double dt);
        void calculateRelativeWindReverse(double dt);

        void calculateAeroProperties();

        void calculateModifiedSections();

        void updatePoints();

        Vector3<real_Num> m_rootLeadingEdge = Vector3<real_Num>::zero();
        Vector3<real_Num> m_rootTrailingEdge = Vector3<real_Num>::zero();
        Vector3<real_Num> m_tipLeadingEdge = Vector3<real_Num>::zero();
        Vector3<real_Num> m_tipTrailingEdge = Vector3<real_Num>::zero();

        Vector3<real_Num> m_rootLiftPosition = Vector3<real_Num>::zero();
        Vector3<real_Num> m_tipLiftPosition = Vector3<real_Num>::zero();

        Vector3<real_Num> m_rootLiftPositionReversed = Vector3<real_Num>::zero();
        Vector3<real_Num> m_tipLiftPositionReversed = Vector3<real_Num>::zero();

        Vector3<real_Num> m_localWingRight = Vector3<real_Num>::zero();

        Vector3<real_Num> m_windRotation = Vector3<real_Num>::zero();

        SmartPtr<CAerofoil> m_aerofoil;
        SmartPtr<IAircraftControlSurface> m_controlSurface;
        SmartPtr<IAircraftPropWash> m_propWash;
        SmartPtr<GroundEffect> m_groundEffect;

        Array<Array<int>> m_debugIds;

        std::array<Vector3<real_Num>, m_maxSections> m_relativeWind;
        std::array<Vector3<real_Num>, m_maxSections> m_relativeWindReversed;

        std::array<Vector3<real_Num>, m_maxSections> m_sectionA;
        std::array<Vector3<real_Num>, m_maxSections> m_sectionB;
        std::array<Vector3<real_Num>, m_maxSections> m_sectionC;
        std::array<Vector3<real_Num>, m_maxSections> m_sectionD;

        std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionA;
        std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionB;
        std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionC;
        std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionD;

        std::array<Vector3<real_Num>, m_maxSections> m_aerodynamicCenters;
        std::array<Vector3<real_Num>, m_maxSections> m_chordLines;
        std::array<Vector3<real_Num>, m_maxSections> m_up;

        std::array<Vector3<real_Num>, m_maxSections> m_aerodynamicCentersReverse;
        std::array<Vector3<real_Num>, m_maxSections> m_chordLinesReverse;
        std::array<Vector3<real_Num>, m_maxSections> m_upReverse;

        std::array<real_Num, m_maxSections> m_aoa;
        std::array<real_Num, m_maxSections> m_aoaReverse;

        std::array<real_Num, m_maxSections> m_chordLengths;
        std::array<real_Num, m_maxSections> m_re;
        std::array<real_Num, m_maxSections> m_area;
        std::array<real_Num, m_maxSections> m_totalLift;
        std::array<real_Num, m_maxSections> m_totalDrag;
        std::array<real_Num, m_maxSections> m_totalPitch;
        std::array<real_Num, m_maxSections> m_fStallControlCL;
        std::array<real_Num, m_maxSections> m_fStallControlCD;
        std::array<real_Num, m_maxSections> m_fStallControlCM;

        real_Num m_liftLineAlphaStart =
            70.0; // AOA at which transition starts
        real_Num m_liftLineAlphaEnd = 110.0; // AOA at which transition ends

        real_Num m_wingTipWidthZeroToOne = 0.0;
        real_Num m_wingTipSweep = 0.0;
        real_Num m_wingTipAngle = 0.0;
        real_Num m_cdOverride = 0.2;
        real_Num m_wingArea = 0.0;

        real_Num m_liftLineChordPosition = 0.0;
        real_Num m_liftLineChordPositionReversed = 0.0;

        real_Num m_liftlineChordTransitionStart = 0.0;
        real_Num m_liftlineChordTransitionEnd = 0.0;

        real_Num m_aoaMultiplier = 1.0;
        real_Num m_cdMultiplier = 1.0;
        real_Num m_clMultiplier = 1.0;
        real_Num m_cmMultiplier = 1.0;

        real_Num m_stallControlCL = 0.0;
        real_Num m_stallControlCD = 0.0;
        real_Num m_stallControlCM = 0.0;
        real_Num m_stallThreshold = 1.0;

        real_Num m_nextUpdateTime = 0.0;
        real_Num m_nextGeometryUpdate = 0.0;

        real_Num m_nextLiftText = 0.0;

        s32 m_sectionCount = 10;

        bool m_isControlSurface = false;
        bool m_useCombinedControlSurface = true;

        Array<int> m_ids;

        /// Used to generate a unique id.
        static u32 m_idExt;
    };

    inline bool CAircraftWing::isControlSurface() const
    {
        return m_isControlSurface;
    }
}

#endif // CAircraftWing_h__
