#ifndef CAircraftWing_h__
#define CAircraftWing_h__

#include "WPVehiclePhysics/WPVehiclePhysicsPrerequisites.hpp"
#include <Workphone/Interface/Vehicle/IAircraftWing.hpp>
#include "WPVehiclePhysics/CAircraftAttachment.hpp"
#include "WPVehiclePhysics/InputController.hpp"
#include "Workphone/Core/Array.hpp"
#include <Workphone/Core/FixedArray.hpp>
#include <Workphone/Core/Properties.hpp>
#include <Workphone/Math/Vector3.hpp>

namespace workphone
{
    namespace vehicle
    {
        /** Class to calculate forces generated by a wing. */
        class WPVehiclePhysics_API CAircraftWing : public CAircraftAttachment<IAircraftWing>
        {
        public:
            static constexpr s32 MaxSections = 10;

            /** Default constructor. Sets up default values. */
            CAircraftWing();
            ~CAircraftWing() override;

            void load( SmartPtr<ISharedObject> data ) override;
            void load( void *pData ) override;
            void unload( SmartPtr<ISharedObject> data ) override;

            void update( const double &t, const double &dt ) override;

            SmartPtr<IAircraftControlSurface> getAttachedControlSurface() const override;
            void                              setAttachedControlSurface(
                SmartPtr<IAircraftControlSurface> attachedControlSurface ) override;

            SmartPtr<IAircraftPropWash> getAttachedPropWash() const override;
            void setAttachedPropWash( SmartPtr<IAircraftPropWash> attachedPropWash ) override;

            bool isControlSurface() const override;
            void setControlSurface( bool bIsControlSurface ) override;

            bool useCombinedControlSurface() const override;
            void setUserCombinedControlSurface( bool bUseCombinedControlSurface ) override;

            void reset() override;

        private:
            void updateGeometry() override;

            real_Num calculateArea( const Vector3<real_Num> &pointA, const Vector3<real_Num> &pointB,
                                    const Vector3<real_Num> &pointC, const Vector3<real_Num> &pointD );

            s32 getDebugId( s32 i ) const;

            s32 getDebugId( s32 section, s32 index ) const;

            void drawGizmos();

            Vector3<real_Num> calculateRelativeWind( s32                      sectionIndex,
                                                     const Vector3<real_Num> &aerodynamicCenter,
                                                     const Vector3<real_Num> &wind );

            Vector3<real_Num> calculateRelativeWind2( s32                      sectionIndex,
                                                      const Vector3<real_Num> &aerodynamicCenter,
                                                      const Vector3<real_Num> &wind );

            Vector3<real_Num> calculateRelativeWind3( s32                      sectionIndex,
                                                      const Vector3<real_Num> &aerodynamicCenter,
                                                      const Vector3<real_Num> &wind );

            void calculateStallControl();
            void calculateForcesSimple( double fDT );
            void calculateForces( double t, double fDT );

            void updateForcesFast( double t, double fDT );

            void calculateAlphaDebug( double t, double dt );
            void calculateAlpha();
            void calculateAlphaReversed();

            void calculateArea();

            void calculateRelativeWindDebug( double dt );

            void calculateRelativeWind( double dt );
            void calculateRelativeWindReverse( double dt );

            void calculateAeroProperties();

            void calculateModifiedSections();

            void updatePoints();

            Vector3<real_Num> m_rootLeadingEdge = Vector3<real_Num>::zero();
            Vector3<real_Num> m_rootTrailingEdge = Vector3<real_Num>::zero();
            Vector3<real_Num> m_tipLeadingEdge = Vector3<real_Num>::zero();
            Vector3<real_Num> m_tipTrailingEdge = Vector3<real_Num>::zero();

            Vector3<real_Num> m_rootLiftPosition = Vector3<real_Num>::zero();
            Vector3<real_Num> m_tipLiftPosition = Vector3<real_Num>::zero();

            Vector3<real_Num> m_rootLiftPositionReversed = Vector3<real_Num>::zero();
            Vector3<real_Num> m_tipLiftPositionReversed = Vector3<real_Num>::zero();

            Vector3<real_Num> m_localWingRight = Vector3<real_Num>::zero();

            Vector3<real_Num> m_windRotation = Vector3<real_Num>::zero();

            SmartPtr<CAerofoil>               m_aerofoil;
            SmartPtr<IAircraftControlSurface> m_controlSurface;
            SmartPtr<IAircraftPropWash>       m_propWash;
            SmartPtr<GroundEffect>            m_groundEffect;

            Array<Array<int>> m_debugIds;

            std::array<Vector3<real_Num>, MaxSections> m_relativeWind;
            std::array<Vector3<real_Num>, MaxSections> m_relativeWindReversed;

            std::array<Vector3<real_Num>, MaxSections> m_sectionA;
            std::array<Vector3<real_Num>, MaxSections> m_sectionB;
            std::array<Vector3<real_Num>, MaxSections> m_sectionC;
            std::array<Vector3<real_Num>, MaxSections> m_sectionD;

            std::array<Vector3<real_Num>, MaxSections> m_modifiedSectionA;
            std::array<Vector3<real_Num>, MaxSections> m_modifiedSectionB;
            std::array<Vector3<real_Num>, MaxSections> m_modifiedSectionC;
            std::array<Vector3<real_Num>, MaxSections> m_modifiedSectionD;

            std::array<Vector3<real_Num>, MaxSections> m_aerodynamicCenters;
            std::array<Vector3<real_Num>, MaxSections> m_chordLines;
            std::array<Vector3<real_Num>, MaxSections> m_up;

            std::array<Vector3<real_Num>, MaxSections> m_aerodynamicCentersReverse;
            std::array<Vector3<real_Num>, MaxSections> m_chordLinesReverse;
            std::array<Vector3<real_Num>, MaxSections> m_upReverse;

            std::array<real_Num, MaxSections> m_aoa;
            std::array<real_Num, MaxSections> m_aoaReverse;

            std::array<real_Num, MaxSections> m_chordLengths;
            std::array<real_Num, MaxSections> m_re;
            std::array<real_Num, MaxSections> m_area;
            std::array<real_Num, MaxSections> m_totalLift;
            std::array<real_Num, MaxSections> m_totalDrag;
            std::array<real_Num, MaxSections> m_totalPitch;
            std::array<real_Num, MaxSections> m_fStallControlCL;
            std::array<real_Num, MaxSections> m_fStallControlCD;
            std::array<real_Num, MaxSections> m_fStallControlCM;

            real_Num m_liftLineAlphaStart =
                static_cast<real_Num>( 70.0 ); // AOA at which transition starts
            real_Num m_liftLineAlphaEnd = static_cast<real_Num>( 110.0 ); // AOA at which transition ends

            real_Num m_wingTipWidthZeroToOne = static_cast<real_Num>( 0.0 );
            real_Num m_wingTipSweep = static_cast<real_Num>( 0.0 );
            real_Num m_wingTipAngle = static_cast<real_Num>( 0.0 );
            real_Num m_cdOverride = static_cast<real_Num>( 0.2 );
            real_Num m_wingArea = static_cast<real_Num>( 0.0 );

            real_Num m_liftLineChordPosition = static_cast<real_Num>( 0.0 );
            real_Num m_liftLineChordPositionReversed = static_cast<real_Num>( 0.0 );

            real_Num m_liftlineChordTransitionStart = static_cast<real_Num>( 0.0 );
            real_Num m_liftlineChordTransitionEnd = static_cast<real_Num>( 0.0 );

            real_Num m_aoaMultiplier = static_cast<real_Num>( 1.0 );
            real_Num m_cdMultiplier = static_cast<real_Num>( 1.0 );
            real_Num m_clMultiplier = static_cast<real_Num>( 1.0 );
            real_Num m_cmMultiplier = static_cast<real_Num>( 1.0 );

            real_Num m_stallControlCL = static_cast<real_Num>( 0.0 );
            real_Num m_stallControlCD = static_cast<real_Num>( 0.0 );
            real_Num m_stallControlCM = static_cast<real_Num>( 0.0 );
            real_Num m_stallThreshold = static_cast<real_Num>( 1.0 );

            real_Num m_nextUpdateTime = 0.0;
            real_Num m_nextGeometryUpdate = 0.0;

            real_Num m_nextLiftText = 0.0;

            s32 m_sectionCount = 10;

            bool m_isControlSurface = false;
            bool m_useCombinedControlSurface = true;

            Array<int> m_ids;

            /// Used to generate a unique id.
            static u32 m_idExt;
        };

        inline bool CAircraftWing::isControlSurface() const
        {
            return m_isControlSurface;
        }
    } // namespace vehicle
} // namespace workphone

#endif // CAircraftWing_h__
