#ifndef CAircraftWingParallel_h__
#define CAircraftWingParallel_h__

#include "WPVehiclePhysics/WPVehiclePhysicsPrerequisites.hpp"
#include <Workphone/Interface/Vehicle/IAircraftWing.hpp>
#include <Workphone/Math/Vector3.hpp>
#include "WPVehiclePhysics/CAircraftAttachment.hpp"
#include <array>

namespace workphone::vehicle
{
    /** Class to calculate forces generated by a wing. */
    class WPVehiclePhysics_API CAircraftWingParallel : public CAircraftAttachment<IAircraftWing>
    {
    public:
        static constexpr s32 m_maxSections = 200;

        /** Default constructor. Sets up default values. */
        CAircraftWingParallel();
        ~CAircraftWingParallel() override;

        void load(SmartPtr<ISharedObject> data) override;
        void load(void *pData) override;

        void update(const double &t, const double &dt) override;

        SmartPtr<IAircraftControlSurface> getAttachedControlSurface() const override;
        void setAttachedControlSurface(
            SmartPtr<IAircraftControlSurface> attachedControlSurface) override;

        SmartPtr<IAircraftPropWash> getAttachedPropWash() const override;
        void setAttachedPropWash(SmartPtr<IAircraftPropWash> attachedPropWash) override;

    private:
        void updateGeometry() override;

        real_Num calculateArea(const Vector3<real_Num> &pointA, const Vector3<real_Num> &pointB,
                               const Vector3<real_Num> &pointC, const Vector3<real_Num> &pointD);

        s32 getDebugId(s32 i) const;

        s32 getDebugId(s32 section, s32 index) const;

        void drawGizmos();

        Vector3<real_Num> calculateRelativeWind(s32 sectionIndex,
                                                const Vector3<real_Num> &aerodynamicCenter,
                                                const Vector3<real_Num> &wind);

        Vector3<real_Num> calculateRelativeWind2(s32 sectionIndex,
                                                 const Vector3<real_Num> &aerodynamicCenter,
                                                 const Vector3<real_Num> &wind);

        Vector3<real_Num> calculateRelativeWind3(s32 sectionIndex,
                                                 const Vector3<real_Num> &aerodynamicCenter,
                                                 const Vector3<real_Num> &wind);

        s32 m_sectionCount;
        real_Num m_wingTipWidthZeroToOne;
        real_Num m_wingTipSweep;
        real_Num m_wingTipAngle;
        real_Num m_cdOverride;
        real_Num m_wingArea;
        real_Num m_liftLineChordPosition;

        real_Num m_aoaMultiplier = 1.0;
        real_Num m_cdMultiplier = 1.0;
        real_Num m_clMultiplier = 1.0;
        real_Num m_cmMultiplier = 1.0;

        real_Num m_stallControlCL = 0.0;
        real_Num m_stallControlCD = 0.0;
        real_Num m_stallControlCM = 0.0;
        real_Num m_stallThreshold = 1.0;

        Vector3<real_Num> m_rootLeadingEdge;
        Vector3<real_Num> m_rootTrailingEdge;
        Vector3<real_Num> m_tipLeadingEdge;
        Vector3<real_Num> m_tipTrailingEdge;
        Vector3<real_Num> m_rootLiftPosition;
        Vector3<real_Num> m_tipLiftPosition;

        Vector3<real_Num> m_localWingRight;

        Vector3<real_Num> m_windRotation = Vector3<real_Num>::zero();

        SmartPtr<CAerofoil> m_aerofoil;
        SmartPtr<IAircraftControlSurface> m_controlSurface;
        SmartPtr<IAircraftPropWash> m_propWash;
        SmartPtr<GroundEffect> m_groundEffect;

        Array<Array<int>> m_debugIds;

        Array<int> m_ids;

        /// Used to generate a unique id.
        static u32 m_idExt;
    };
}

#endif // CAircraftWingParallel_h__
