#ifndef WingFast_h__
#define WingFast_h__

#include <Workphone/WorkphonePrerequisites.hpp>
#include <Workphone/Interface/Vehicle/IAircraftWing.hpp>
#include "WPVehiclePhysics/WPVehiclePhysicsPrerequisites.hpp"
#include <Workphone/Math/Vector3.hpp>
#include "WPVehiclePhysics/CAircraftAttachment.hpp"
#include "WPVehiclePhysics/InputController.hpp"
#include "Workphone/Core/Array.hpp"
#include <Workphone/Core/Properties.hpp>
#include <Workphone/Core/FixedArray.hpp>

namespace workphone
{
    namespace vehicle
    {
        /** Class to calculate forces generated by a wing. */
        class WPVehiclePhysics_API CAircraftWingFast : public CAircraftAttachment<IAircraftWing>
        {
        public:
            static constexpr s32 m_maxSections = 10;

            /** Default constructor. Sets up default values. */
            CAircraftWingFast();
            ~CAircraftWingFast() override;

            void load( SmartPtr<ISharedObject> data ) override;
            void load( void *pData ) override;
            void unload( SmartPtr<ISharedObject> data ) override;

            void update( const double &t, const double &dt ) override;
            void updateWorker();

            void calculateStallControl();
            void calculateForces( double fDT );

            void updateForces();

            void updateForcesFast();
            void calculateAlphaMinus10();
            void calculateAlpha10();
            void calculateAlpha();

            void calculateAera();

            void calculateRelativeWind();

            void calculateRelativeWindMinus10();
            void calculateRelativeWindPlus10();
            void calculateAeroProperties();

            void calculateAeroProperties10();
            void calculateAeroPropertiesMinus10();
            void calculateModifiedSections();

            void calculateModifiedSections10();

            void calculateModifiedSectionsMinus10();
            void updatePoints();
            void updateVisualPoints();

            void updateCombined( const double &t, const double &fDT );
            void updateSeparate( const double &t, const double &fDT );

            SmartPtr<IAircraftControlSurface> getAttachedControlSurface() const override;
            void                              setAttachedControlSurface(
                SmartPtr<IAircraftControlSurface> attachedControlSurface ) override;

            SmartPtr<IAircraftPropWash> getAttachedPropWash() const override;
            void setAttachedPropWash( SmartPtr<IAircraftPropWash> attachedPropWash ) override;

            bool isControlSurface() const override;
            void setControlSurface( bool bIsControlSurface ) override;

            bool useCombinedControlSurface() const override;
            void setUserCombinedControlSurface( bool bUseCombinedControlSurface ) override;

        private:
            void updateGeometry() override;

            real_Num calculateArea( const Vector3<real_Num> &pointA, const Vector3<real_Num> &pointB,
                                    const Vector3<real_Num> &pointC, const Vector3<real_Num> &pointD );

            s32 getDebugId( s32 i ) const;

            s32 getDebugId( s32 section, s32 index ) const;

            void drawGizmos();

            Vector3<real_Num> calculateRelativeWind( s32                      sectionIndex,
                                                     const Vector3<real_Num> &aerodynamicCenter,
                                                     const Vector3<real_Num> &wind );

            Vector3<real_Num> calculateRelativeWind2( s32                      sectionIndex,
                                                      const Vector3<real_Num> &aerodynamicCenter,
                                                      const Vector3<real_Num> &wind );

            Vector3<real_Num> calculateRelativeWind3( s32                      sectionIndex,
                                                      const Vector3<real_Num> &aerodynamicCenter,
                                                      const Vector3<real_Num> &wind );

            bool m_isControlSurface = false;
            bool m_useCombinedControlSurface = true;

            s32      m_sectionCount = 10;
            real_Num m_wingTipWidthZeroToOne = static_cast<real_Num>( 0.0 );
            real_Num m_wingTipSweep = static_cast<real_Num>( 0.0 );
            real_Num m_wingTipAngle = static_cast<real_Num>( 0.0 );
            real_Num m_cdOverride = static_cast<real_Num>( 0.0 );
            real_Num m_wingArea = static_cast<real_Num>( 0.0 );
            real_Num m_liftLineChordPosition = static_cast<real_Num>( 0.0 );

            real_Num m_aoaMultiplier = static_cast<real_Num>( 1.0 );
            real_Num m_cdMultiplier = static_cast<real_Num>( 1.0 );
            real_Num m_clMultiplier = static_cast<real_Num>( 1.0 );
            real_Num m_cmMultiplier = static_cast<real_Num>( 1.0 );

            real_Num m_stallControlCL = static_cast<real_Num>( 0.0 );
            real_Num m_stallControlCD = static_cast<real_Num>( 0.0 );
            real_Num m_stallControlCM = static_cast<real_Num>( 0.0 );
            real_Num m_stallThreshold = static_cast<real_Num>( 1.0 );

            Vector3<real_Num> m_rootLeadingEdge;
            Vector3<real_Num> m_rootTrailingEdge;
            Vector3<real_Num> m_tipLeadingEdge;
            Vector3<real_Num> m_tipTrailingEdge;
            Vector3<real_Num> m_rootLiftPosition;
            Vector3<real_Num> m_tipLiftPosition;

            Vector3<real_Num> m_localWingRight;

            Vector3<real_Num> m_windRotation = Vector3<real_Num>::zero();

            SmartPtr<CAerofoil>               m_aerofoil;
            SmartPtr<IAircraftControlSurface> m_controlSurface;
            SmartPtr<IAircraftPropWash>       m_propWash;
            SmartPtr<GroundEffect>            m_groundEffect;

            Array<Array<int>> m_debugIds;

            std::array<Vector3<real_Num>, m_maxSections> m_relativeWind;
            std::array<Vector3<real_Num>, m_maxSections> m_relativeWindPlus10;
            std::array<Vector3<real_Num>, m_maxSections> m_relativeWindMinus10;

            std::array<Vector3<real_Num>, m_maxSections> m_currentRelativeWind;

            std::array<Vector3<real_Num>, m_maxSections> m_sectionA;
            std::array<Vector3<real_Num>, m_maxSections> m_sectionB;
            std::array<Vector3<real_Num>, m_maxSections> m_sectionC;
            std::array<Vector3<real_Num>, m_maxSections> m_sectionD;

            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionA;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionB;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionC;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionD;

            std::array<Vector3<real_Num>, m_maxSections> m_visualSectionA;
            std::array<Vector3<real_Num>, m_maxSections> m_visualSectionB;
            std::array<Vector3<real_Num>, m_maxSections> m_visualSectionC;
            std::array<Vector3<real_Num>, m_maxSections> m_visualSectionD;

            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionA10;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionB10;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionC10;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionD10;

            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionAMinus10;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionBMinus10;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionCMinus10;
            std::array<Vector3<real_Num>, m_maxSections> m_modifiedSectionDMinus10;

            std::array<Vector3<real_Num>, m_maxSections> m_aerodynamicCenters;
            std::array<Vector3<real_Num>, m_maxSections> m_aerodynamicCentersPlus10;
            std::array<Vector3<real_Num>, m_maxSections> m_aerodynamicCentersMinus10;

            std::array<Vector3<real_Num>, m_maxSections> m_chordLines;
            std::array<Vector3<real_Num>, m_maxSections> m_chordLinesPlus10;
            std::array<Vector3<real_Num>, m_maxSections> m_chordLinesMinus10;

            std::array<Vector3<real_Num>, m_maxSections> m_up;
            std::array<Vector3<real_Num>, m_maxSections> m_upPlus10;
            std::array<Vector3<real_Num>, m_maxSections> m_upMinus10;

            std::array<real_Num, m_maxSections> m_aoa;
            std::array<real_Num, m_maxSections> m_aoaPlus10;
            std::array<real_Num, m_maxSections> m_aoaMinus10;

            std::array<real_Num, m_maxSections> m_chordLengthsMinus10;
            std::array<real_Num, m_maxSections> m_chordLengthsPlus10;
            std::array<real_Num, m_maxSections> m_chordLengths;

            std::array<real_Num, m_maxSections> m_re;
            std::array<real_Num, m_maxSections> m_area;

            std::array<real_Num, m_maxSections> m_totalLift;
            std::array<real_Num, m_maxSections> m_totalDrag;
            std::array<real_Num, m_maxSections> m_totalPitch;

            std::array<real_Num, m_maxSections> m_fStallControlCL;
            std::array<real_Num, m_maxSections> m_fStallControlCD;
            std::array<real_Num, m_maxSections> m_fStallControlCM;

            real_Num m_nextUpdateTime = 0.0;
            real_Num m_nextGeometryUpdate = 0.0;

            Array<int> m_ids;

            /// Used to generate a unique id.
            static u32 m_idExt;
        };

        inline bool CAircraftWingFast::isControlSurface() const
        {
            return m_isControlSurface;
        }
    } // namespace vehicle
} // namespace workphone

#endif // Wing_h__
