#ifndef RotorSector_h__
#define RotorSector_h__

#include "WPVehiclePhysics/WPVehiclePhysicsPrerequisites.hpp"
#include "WPVehiclePhysics/Surface.hpp"
#include "VecMath.hpp"
#include <string>
#include <array>
#include <memory>

namespace workphone
{
    namespace vehicle
    {
        /**
         * @brief Represents a rotor sector containing a set of surface elements
         *        (arc segments) and aggregated time-averaged results for that
         *        sector.
         *
         * A rotor is divided into sectors (azimuthal slices). Each sector
         * contains an array of TSurface elements that model the aerodynamic
         * properties across the radial/arc discretisation. The class also
         * stores aggregated, time-averaged force and power for the sector.
         */
        class TRotorSector
        {
        public:
            /// Default constructor
            TRotorSector();

            /// Non-copyable: disable copy construction to avoid accidental sharing
            TRotorSector( const TRotorSector &other ) = delete;

            /**
             * @brief Array of surface elements that make up the rotor sector.
             *
             * The array size is 21 with a convention that valid element
             * indices are in the range 1..20. Index 0 is unused to simplify
             * 1-based indexing in algorithms that iterate blade elements.
             */
            std::array<TSurface, 21> m_arc;

            /**
             * @brief Time-averaged sum of forces generated by all elements in
             *        this sector. This is a vector in world/local coordinates
             *        depending on how callers use it.
             */
            physics_Vec m_secForce = physics_Vec::zero();

            /**
             * @brief Time-averaged mechanical power produced/consumed by this
             *        sector (units depend on simulation configuration).
             */
            real_dNum m_secPower = 0.0;
        }; // TRotorSector
    } // namespace vehicle
} // namespace workphone

#endif // RotorSector_h__
