if (APPLE)
    project(WPOISInput C CXX OBJC)
else()
    project(WPOISInput C CXX)
endif()

# define header and source files for the library
file(GLOB HEADER_FILES "../../Include/WPOISInput/*.hpp" "../../Include/WPOISInput/*.hpppp" "../../Include/WPOISInput/*.inl")
file(GLOB SOURCE_FILES "../../Source/WPOISInput/*.cpp" "../../Source/WPOISInput/*.c")

set(WP_HEADER_REL_PATH "${WP_ROOT}/Engine/cpp/Project/WPOISInput/../../Include/WPOISInput")
set(WP_SOURCE_REL_PATH "${WP_ROOT}/Engine/cpp/Project/WPOISInput/../../Source/WPOISInput")

file(GLOB HEADER_FILES_OGRE_INCLUDE_OSX "../../Include/WPOISInput/Extern/OIS/*.hpp")
file(GLOB SOURCE_FILES_OGRE_INCLUDE_OSX "../../Source/WPOISInput/Extern/OIS/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_OGRE_INCLUDE_OSX})
list(APPEND SOURCE_FILES ${SOURCE_FILES_OGRE_INCLUDE_OSX})

if (WIN32)
    file(GLOB_RECURSE HEADER_FILES_OGRE_INCLUDE_WIN32 "../../Include/WPOISInput/Extern/OIS/win32/*.hpp")
    file(GLOB_RECURSE SOURCE_FILES_OGRE_SOURCE_WIN32 "../../Source/WPOISInput/Extern/OIS/win32/*.cpp")
    list(APPEND HEADER_FILES ${HEADER_FILES_OGRE_INCLUDE_WIN32})
    list(APPEND SOURCE_FILES ${SOURCE_FILES_OGRE_SOURCE_WIN32})

    file(GLOB_RECURSE HEADER_FILES_OGRE_INCLUDE_WIN32 "../../Include/WPOISInput/Platform/win32/*.hpp")
    file(GLOB_RECURSE SOURCE_FILES_OGRE_SOURCE_WIN32 "../../Source/WPOISInput/Platform/win32/*.cpp")
    list(APPEND HEADER_FILES ${HEADER_FILES_OGRE_INCLUDE_WIN32})
    list(APPEND SOURCE_FILES ${SOURCE_FILES_OGRE_SOURCE_WIN32})
elseif(APPLE)
    set(CMAKE_MACOSX_RPATH 1)
    find_library(COCOA_LIBRARY Cocoa)
    find_library(FOUNDATION_LIBRARY Foundation)
    find_library(IOKIT_LIBRARY IOKit)
    find_path(COCOA_INCLUDE_DIR Cocoa/Cocoa.hpp)
    find_library(CARBON_LIBRARY Carbon)

    add_definitions(-x objective-c++)

    file(GLOB_RECURSE HEADER_FILES_OGRE_INCLUDE_OSX "../../Include/WPOISInput/Extern/OIS/mac/*.hpp")
    file(GLOB_RECURSE SOURCE_FILES_OGRE_INCLUDE_OSX "../../Source/WPOISInput/Extern/OIS/mac/*.cpp" "../../Source/WPOISInput/Extern/OIS/mac/*.mm")
    list(APPEND HEADER_FILES ${HEADER_FILES_OGRE_INCLUDE_OSX})
    list(APPEND SOURCE_FILES ${SOURCE_FILES_OGRE_INCLUDE_OSX})

    file(GLOB_RECURSE HEADER_FILES_OGRE_INCLUDE_OSX "../../Include/WPOISInput/Platform/macOS/*.hpp")
    file(GLOB_RECURSE SOURCE_FILES_OGRE_INCLUDE_OSX "../../Source/WPOISInput/Platform/macOS/*.cpp" "../../Source/WPOISInput/Platform/macOS/*.mm")
    list(APPEND HEADER_FILES ${HEADER_FILES_OGRE_INCLUDE_OSX})
    list(APPEND SOURCE_FILES ${SOURCE_FILES_OGRE_INCLUDE_OSX})
elseif(UNIX)
    file(GLOB_RECURSE HEADER_FILES_OGRE_INCLUDE_UNIX "../../Include/WPOISInput/Extern/OIS/linux/*.hpp")
    file(GLOB_RECURSE SOURCE_FILES_OGRE_INCLUDE_UNIX "../../Source/WPOISInput/Extern/OIS/linux/*.cpp")
    list(APPEND HEADER_FILES ${HEADER_FILES_OGRE_INCLUDE_UNIX})
    list(APPEND SOURCE_FILES ${SOURCE_FILES_OGRE_INCLUDE_UNIX})
endif()

foreach(_source IN ITEMS ${HEADER_FILES})
    get_filename_component(_source_file_path "${_source}" DIRECTORY)
    string(REPLACE "${WP_HEADER_REL_PATH}" "" _group_file_path "${_source_file_path}")
    string(REPLACE "/" "\\" _group_file_path "${_group_file_path}")
    source_group("Header Files\\${_group_file_path}" FILES "${_source}")
endforeach()

foreach(_source IN ITEMS ${SOURCE_FILES})
    get_filename_component(_source_file_path "${_source}" DIRECTORY)
    string(REPLACE "${WP_SOURCE_REL_PATH}" "" _group_file_path "${_source_file_path}")
    string(REPLACE "/" "\\" _group_file_path "${_group_file_path}")
    source_group("Source Files\\${_group_file_path}" FILES "${_source}")
endforeach()

if (UNIX)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
endif()

include_directories( ${WP_ROOT}/Dependencies/boost )

if (WP_USE_ONETBB)
    include_directories( ${CMAKE_SOURCE_DIR}/Dependencies/onetbb/include )
elseif (WP_USE_TBB)
    include_directories( ${CMAKE_SOURCE_DIR}/Dependencies/tbb/include )
endif()

include_directories( ${WP_ROOT}/Dependencies/tinybind )
include_directories( ${WP_ROOT}/Dependencies/tinyxml )
include_directories( ${WP_ROOT}/Dependencies/utf8/source )
include_directories( ${WP_ROOT}/AdditionalLibraries/zlib )
include_directories( ${WP_ROOT}/AdditionalLibraries/zlib/src )
include_directories( ${WP_ROOT}/AdditionalLibraries/zlib/src/contrib/minizip )
include_directories( ${WP_ROOT}/AdditionalLibraries/zziplib )
include_directories( ../../Include )
include_directories( ../../Include/WPOISInput/Extern )
include_directories( ../../Include/WPOISInput/Extern/OIS )

if (NOT WP_STATIC_LIB)
    if (WIN32)
        link_directories(WPOISInput ${CMAKE_SOURCE_DIR}/libs/windows/${WP_TOOLSET}/${WP_ARCH}/${WP_STATIC_LINK_CRT_TYPE}/${CMAKE_BUILD_TYPE})
    endif()
endif()

if (WP_STATIC_LIB)
    add_library(WPOISInput STATIC ${HEADER_FILES} ${SOURCE_FILES})
else ()
    add_library(WPOISInput SHARED ${HEADER_FILES} ${SOURCE_FILES})
endif()

if (NOT WP_STATIC_LIB)
    if (WIN32)
        target_link_libraries(WPOISInput Workphone.lib)

        if (WP_USE_ONETBB)
            target_link_libraries(WPOISInput debug tbb12_debug.lib optimized tbb12.lib)
            target_link_libraries(WPOISInput debug tbbmalloc_debug.lib optimized tbbmalloc.lib)
            target_link_libraries(WPOISInput debug tbbmalloc_proxy_debug.lib optimized tbbmalloc_proxy.lib)
        elseif (WP_USE_TBB)
            if (TBB_BUILD__STATIC)
                target_link_libraries(WPOISInput tbb_static.lib)
                target_link_libraries(WPOISInput tbbmalloc_static.lib)
            else()
                target_link_libraries(WPOISInput tbb.lib)
			    target_link_libraries(WPOISInput tbbmalloc.lib)
            endif()
        endif()

        target_link_libraries(WPOISInput dinput8.lib)
        target_link_libraries(WPOISInput dxguid.lib)

        target_link_libraries(WPOISInput harfbuzz.lib)
        target_link_libraries(WPOISInput harfbuzz-subset.lib)
        target_link_libraries(WPOISInput icucommon.lib)
        target_link_libraries(WPOISInput sds_library.lib)

        target_link_libraries(WPOISInput bcrypt.lib)
        target_link_libraries(WPOISInput libboost_thread.lib)
        target_link_libraries(WPOISInput libboost_date_time.lib)
        target_link_libraries(WPOISInput libboost_chrono.lib)
        target_link_libraries(WPOISInput libboost_timer.lib)
        target_link_libraries(WPOISInput libboost_filesystem.lib)
        target_link_libraries(WPOISInput libboost_json.lib)
        target_link_libraries(WPOISInput minizip.lib)
        target_link_libraries(WPOISInput nativefiledialog.lib)
        target_link_libraries(WPOISInput rttr.lib)
        target_link_libraries(WPOISInput tinyxml.lib)   
        target_link_libraries(WPOISInput yaml-cpp.lib)
        target_link_libraries(WPOISInput zlib.lib)
        target_link_libraries(WPOISInput zzip.lib)
    elseif (APPLE)
        target_link_libraries(WPOISInput libWorkphone.a)
        target_link_libraries(WPOISInput libFBMesh.a)
        target_link_libraries(WPOISInput libWPProcedural.a)
        target_link_libraries(WPOISInput libWPAssimp.a)

        if (WP_BUILD_AUDIO)
            target_link_libraries(WPOISInput WPOISInput.a)
        endif()

        if (WP_ENABLE_LUA)
            target_link_libraries(WPOISInput WPLua.a)
            target_link_libraries(WPOISInput WPLuaBind.a)
        elseif (WP_ENABLE_PYTHON)
            target_link_libraries(WPOISInput WPPython.a)
            target_link_libraries(WPOISInput WPPythonBind.a)
        endif()

        if (WP_BUILD_SDL2)
            target_link_libraries(WPOISInput SDL2main.a)
            target_link_libraries(WPOISInput SDL2_image.a)
            target_link_libraries(WPOISInput debug SDL2d.a optimized SDL2.a)
        endif()

        if (WP_BUILD_IMGUI)
            target_link_libraries(WPOISInput libWPImGui.a)
            target_link_libraries(WPOISInput imgui.a)
        endif()

        if (WP_BUILD_PHYSX)
            target_link_libraries(WPOISInput libWPPhysx.a)
        elseif (WP_BUILD_ODE)
            target_link_libraries(WPOISInput libWPODE3.a)
        endif()

        if (WP_BUILD_OISINPUT)
            target_link_libraries(WPOISInput libWPOISInput.a)
            #target_link_libraries(WPOISInput debug libOIS_d.a optimized libOIS.a)
        endif()

        target_link_libraries(WPOISInput libWPVehiclePhysics.a)

        if (WP_BUILD_WXWIDGETS)
            #target_link_libraries(WPOISInput libWPWxWidgets.a)

            target_link_libraries(WPOISInput libwx_osx_cocoau_core-3.1.a)
            target_link_libraries(WPOISInput libwx_baseu-3.1.a)
            target_link_libraries(WPOISInput libwx_osx_cocoau_xrc-3.1.a)
            target_link_libraries(WPOISInput libwx_osx_cocoau_propgrid-3.1.a)
            target_link_libraries(WPOISInput libwx_osx_cocoau_richtext-3.1.a)
            target_link_libraries(WPOISInput libwxexpat-3.1.a)
            target_link_libraries(WPOISInput libwx_baseu_xml-3.1.a)
            target_link_libraries(WPOISInput libwx_baseu_net-3.1.a)
            target_link_libraries(WPOISInput libwx_osx_cocoau_webview-3.1.a)
            target_link_libraries(WPOISInput libwx_osx_cocoau_xrc-3.1.a)
            target_link_libraries(WPOISInput libwx_osx_cocoau_adv-3.1.a)
            target_link_libraries(WPOISInput libwx_osx_cocoau_aui-3.1.a)
            target_link_libraries(WPOISInput libwx_osx_cocoau_html-3.1.a)
            target_link_libraries(WPOISInput libwxtiff-3.1.a)
            target_link_libraries(WPOISInput libwxjpeg-3.1.a)
            target_link_libraries(WPOISInput libwxpng-3.1.a)

            target_link_libraries(WPOISInput libiconv.a)
        endif()

        target_link_libraries(WPOISInput libFBRenderUI.a)
        target_link_libraries(WPOISInput libWPSQLite.a)
        target_link_libraries(WPOISInput libFBCPlusPlus.a)
        target_link_libraries(WPOISInput libFBGraphics.a)

        target_link_libraries(WPOISInput libboost_thread.a)
        target_link_libraries(WPOISInput libboost_date_time.a)
        target_link_libraries(WPOISInput libboost_chrono.a)
        target_link_libraries(WPOISInput libboost_timer.a)
        target_link_libraries(WPOISInput libboost_filesystem.a)
        target_link_libraries(WPOISInput libboost_json.a)

        if (WP_BUILD_PHYSX)
            target_link_libraries(WPOISInput WPPhysx.a)

            target_link_libraries(WPOISInput PhysX3.a)
            target_link_libraries(WPOISInput PhysX3Extensions.a)
            target_link_libraries(WPOISInput PhysX3Common.a)
            target_link_libraries(WPOISInput PhysX3Vehicle.a)
            target_link_libraries(WPOISInput PhysX3Cooking.a)
            target_link_libraries(WPOISInput PhysXProfileSDK.a)
            target_link_libraries(WPOISInput PxTask.a)
            target_link_libraries(WPOISInput PhysXVisualDebuggerSDK.a)
            target_link_libraries(WPOISInput PhysX3MetaData.a)
            target_link_libraries(WPOISInput PhysX3Foundation.a)
            target_link_libraries(WPOISInput PxSceneQuery.a)
            target_link_libraries(WPOISInput PxSimulationController.a)
            target_link_libraries(WPOISInput PhysX3LowLevel.a)
            target_link_libraries(WPOISInput PhysX3LowLevelCloth.a)
        endif()

        if (WP_USE_TBB)
            target_link_libraries(WPOISInput libtbb.a)
            target_link_libraries(WPOISInput libtbbmalloc.a)
        endif()

        target_link_libraries(WPOISInput minizip.a)
        target_link_libraries(WPOISInput nativefiledialog.a)
        target_link_libraries(WPOISInput rttr.a)
        target_link_libraries(WPOISInput tinyxml.a)
        target_link_libraries(WPOISInput yaml-cpp.a)
        target_link_libraries(WPOISInput zlib.a)
        target_link_libraries(WPOISInput zzip.a)

        if (WP_BUILD_WILDMAGIC5)
            target_link_libraries(WPOISInput libWm5Core.a)
            target_link_libraries(WPOISInput libWm5Mathematics.a)
        endif()

        if (WP_USE_ASSET_IMPORT)
            #target_link_libraries(WPOISInput debug libassimpd.a optimized libassimp.a)
        endif()

        if (WP_CODEC_FREEIMAGE)
            target_link_libraries(WPOISInput FreeImage.a)
        endif()

        if (WP_USE_FREETYPE)
            target_link_libraries(WPOISInput freetype.a)
        endif()

        if (WP_GRAPHICS_SYSTEM_OGRENEXT)
            target_link_libraries(WPOISInput WPOISInput.a)
            target_link_libraries(WPOISInput harfbuzz.a)
            target_link_libraries(WPOISInput harfbuzz-subset.a)
            target_link_libraries(WPOISInput icucommon.a)
            target_link_libraries(WPOISInput sds_library.a)
        elseif (WP_GRAPHICS_SYSTEM_OGRE)
            target_link_libraries(WPOISInput WPGraphicsOgre.a)
        endif()

        #target_link_libraries(OgreOverlayTest stdc++ "-framework CoreGraphics" objc)
        #target_link_libraries(OgreOverlayTest ${AUDIO_UNIT})
        target_link_libraries(WPOISInput stdc++ "-framework AppKit" "-framework Metal" "-framework MetalKit" "-framework OpenGL" "-framework Foundation" "-framework QuartzCore" "-framework CoreGraphics" "-framework CoreServices" "-framework Cocoa" "-framework Carbon" "-framework IOKit" "-framework GameController" objc)
        set_target_properties(WPOISInput PROPERTIES LINK_FLAGS "-Wl,-F/Library/Frameworks")
    elseif (UNIX)
        target_link_libraries(WPOISInput -Wl,--start-group Workphone.a WPVehiclePhysics.a libWPProcedural.a WPImGui.a
            FBMath.a FBMesh.a WPOISInput.a WPVehiclePhysics.a FBData.a FBState.a libWPPhysx.a libWPSQLite.a
            libWPVehiclePhysics.a FBGraphics.a WPOISInput.a WPAssimp.a FBRenderUI.a libFBCPlusPlus.a
            libboost_thread-gcc5-mt-s-x64-1_70.a
            libboost_date_time-gcc5-mt-s-x64-1_70.a
            libboost_chrono-gcc5-mt-s-x64-1_70.a
            libboost_timer-gcc5-mt-s-x64-1_70.a
            libboost_filesystem-gcc5-mt-s-x64-1_70.a
            debug libtbb_debug.a optimized libtbb.a
            debug libtbbmalloc_debug.a optimized libtbbmalloc.a
            libWm5Core.a libWm5Mathematics.a
            libLowLevel.a libLowLevelCloth.a libPhysXProfileSDK.a libPhysX3Common.a libSceneQuery.a 
            libSimulationController.a libPhysX3Cooking.a libPhysX3Extensions.a libPhysX3.a libPhysX3Vehicle.a libPxTask.a
            -Wl,--end-group )

        if (WP_GRAPHICS_SYSTEM_OGRENEXT)
            target_link_libraries(WPOISInput WPOISInput.a)
            target_link_libraries(WPOISInput freetype.a)
        elseif(WP_GRAPHICS_SYSTEM_SOFTWARE)
            target_link_libraries(WPOISInput libFBGraphicsSoftware.a)
        endif()

        target_link_libraries(WPOISInput png)
        target_link_libraries(WPOISInput Xaw)
        target_link_libraries(WPOISInput Xrandr)
        target_link_libraries(WPOISInput Xt)
        target_link_libraries(WPOISInput xcb)
        target_link_libraries(WPOISInput GL)
        target_link_libraries(WPOISInput ${X11_LIBRARIES})
        target_link_libraries(WPOISInput ${CMAKE_THREAD_LIBS_INIT} )
        target_link_libraries(WPOISInput ${CMAKE_DL_LIBS})
    endif ()
endif()

set_target_properties (WPOISInput PROPERTIES FOLDER Engine/Cpp/Input)

if (NOT WP_STATIC_LIB)
	target_compile_definitions(WPOISInput PUBLIC WPOISInput_EXPORTS)
endif()

if (NOT WP_STATIC_LIB)
    add_dependencies(WPOISInput Workphone)
endif()
