#ifndef __WP_CoreHeaders_h__
#define __WP_CoreHeaders_h__

#include <Workphone/ApplicationUtil.hpp>
#include <Workphone/AI/AiManager.hpp>

#include <Workphone/Animation/ActorAnimationTrack.hpp>
#include <Workphone/Animation/Animation.hpp>
#include <Workphone/Animation/AnimationEventTimeline.hpp>
#include <Workphone/Animation/AnimationFrameTime.hpp>
#include <Workphone/Animation/AnimationGraph.hpp>
#include <Workphone/Animation/AnimationInterface.hpp>
#include <Workphone/Animation/AnimationKeyFrame.hpp>
#include <Workphone/Animation/AnimationSyncTrack.hpp>
#include <Workphone/Animation/IK/AnimationIKSystem.hpp>
#include <Workphone/Animation/IK/TwoBoneIK.hpp>
#include <Workphone/Animation/InterpolateAnimator.hpp>

// core
#include <Workphone/Core/BitUtil.hpp>
#include <Workphone/Core/ColourF.hpp>
#include <Workphone/Core/DataUtil.hpp>
#include <Workphone/Core/DebugTrace.hpp>
#include <Workphone/Core/Handle.hpp>
#include <Workphone/Core/Image.hpp>
#include <Workphone/Core/JsonParser.hpp>
#include <Workphone/Core/LogManager.hpp>
#include <Workphone/Core/LogManagerDefault.hpp>
#include <Workphone/Core/Node.hpp>
#include <Workphone/Core/ParameterUtil.hpp>
#include <Workphone/Core/Path.hpp>
#include <Workphone/Core/PluginMacros.hpp>
#include <Workphone/Core/Properties.hpp>
#include <Workphone/Core/PropertiesBinarySerializer.hpp>
#include <Workphone/Core/Resolution.hpp>
#include <Workphone/Core/Util.hpp>
#include <Workphone/Core/VectorUtil.hpp>
#include <Workphone/Core/XmlUtil.hpp>

// database
#include <Workphone/Database/DatabaseManager.hpp>
#include <Workphone/Database/AssetDatabaseManager.hpp>
#include <Workphone/Database/ResourceDatabase.hpp>

// graphics
#include <Workphone/Graphics/GraphicsSettings.hpp>
#include <Workphone/Graphics/GraphicsSystem.hpp>
#include <Workphone/Graphics/GraphicsSceneNode.hpp>
#include <Workphone/Graphics/RenderTarget.hpp>
#include <Workphone/Graphics/RenderTargetListener.hpp>
#include <Workphone/Graphics/RenderTexture.hpp>
#include <Workphone/Graphics/GraphicsUtil.hpp>
#include <Workphone/Graphics/GraphicsWindow.hpp>

// input
#include <Workphone/Input/AxisData.hpp>
#include <Workphone/Input/GameInput.hpp>
#include <Workphone/Input/GameInputState.hpp>
#include <Workphone/Input/GameInputMap.hpp>
#include <Workphone/Input/InputActionData.hpp>
#include <Workphone/Input/InputDeviceManager.hpp>
#include <Workphone/Input/InputEvent.hpp>
#include <Workphone/Input/InputManager.hpp>
#include <Workphone/Input/Joystick.hpp>
#include <Workphone/Input/JoystickState.hpp>
#include <Workphone/Input/KeyboardState.hpp>
#include <Workphone/Input/MouseState.hpp>

#include <Workphone/WorkphoneInterface.hpp>

// io
#include <Workphone/IO/FileDataStream.hpp>
#include <Workphone/IO/FileSystem.hpp>
#include <Workphone/IO/ZipUtil.hpp>

// jobs
#include <Workphone/Jobs/ActorEnableJob.hpp>
#include <Workphone/Jobs/CameraManagerReset.hpp>
#include <Workphone/Jobs/CreateRigidBodies.hpp>
#include <Workphone/Jobs/EventJob.hpp>
#include <Workphone/Jobs/FlagSetJob.hpp>
#include <Workphone/Jobs/ImportResourceJob.hpp>
#include <Workphone/Jobs/ObjectUpdateJob.hpp>
#include <Workphone/Jobs/LoadPluginJob.hpp>
#include <Workphone/Jobs/UnloadPluginJob.hpp>

// math
#include <Workphone/Math/Euler.hpp>
#include <Workphone/Math/MathUtil.hpp>
#include <Workphone/Math/Line2.hpp>
#include <Workphone/Math/Line3.hpp>
#include <Workphone/Math/LinearSpline1.hpp>
#include <Workphone/Math/LinearSpline2.hpp>
#include <Workphone/Math/LinearSpline3.hpp>
#include <Workphone/Math/LinearSpline4.hpp>
#include <Workphone/Math/Ray3.hpp>
#include <Workphone/Math/Rect.hpp>
#include <Workphone/Math/RotationalSpline3.hpp>
#include <Workphone/Math/Matrix2.hpp>
#include <Workphone/Math/Matrix3.hpp>
#include <Workphone/Math/Matrix4.hpp>
#include <Workphone/Math/OBB3.hpp>
#include <Workphone/Math/PerlinNoiseGenerator.hpp>
#include <Workphone/Math/Plane3.hpp>
#include <Workphone/Math/Polygon2.hpp>
#include <Workphone/Math/Polygon3.hpp>
#include <Workphone/Math/Segment.hpp>
#include <Workphone/Math/Smooth.hpp>
#include <Workphone/Math/Sphere2.hpp>
#include <Workphone/Math/Sphere3.hpp>
#include <Workphone/Math/Transform2.hpp>
#include <Workphone/Math/Transform3.hpp>
#include <Workphone/Math/Triangle3.hpp>
#include <Workphone/Math/Vector2.hpp>
#include <Workphone/Math/Vector3.hpp>
#include <Workphone/Math/Vector4.hpp>
#include <Workphone/Math/VectorRate.hpp>

// mesh
#include <Workphone/Mesh/FoliageLoader.hpp>
#include <Workphone/Mesh/Mesh.hpp>
#include <Workphone/Mesh/MeshConverter.hpp>
#include <Workphone/Mesh/MeshUtil.hpp>
#include <Workphone/Mesh/ProgressiveMeshOptions.hpp>
#include <Workphone/Mesh/VertexBuffer.hpp>
#include <Workphone/Mesh/IndexBuffer.hpp>
#include <Workphone/Mesh/SubMesh.hpp>
#include <Workphone/Mesh/VertexDeclaration.hpp>
#include <Workphone/Mesh/MeshResource.hpp>
#include <Workphone/Mesh/MeshManager.hpp>
#include <Workphone/Mesh/MeshSerializer.hpp>
#include <Workphone/Mesh/MeshSkeleton.hpp>
#include <Workphone/Mesh/CollisionMesh.hpp>
#include <Workphone/Mesh/CollisionSubMesh.hpp>
#include <Workphone/Mesh/VertexBoneAssignment.hpp>

// memory
#include <Workphone/Memory/Data.hpp>
#include <Workphone/Memory/FactoryUtil.hpp>
#include <Workphone/Memory/Memory.hpp>
#include <Workphone/Memory/MemoryTracker.hpp>
#include <Workphone/Memory/SharedObjectTracker.hpp>
#include <Workphone/Memory/TypeManager.hpp>

#include <Workphone/Physics/RaycastHit.hpp>

// scene
#include <Workphone/Scene/Components/Animation.hpp>
#include <Workphone/Scene/Components/AnimatedMaterial.hpp>
#include <Workphone/Scene/Components/Animator.hpp>
#include <Workphone/Scene/Components/AudioEmitter.hpp>
#include <Workphone/Scene/Components/Billboard.hpp>
#include <Workphone/Scene/Components/Billboards.hpp>
#include <Workphone/Scene/Components/CarController.hpp>
#include <Workphone/Scene/Components/Camera.hpp>
#include <Workphone/Scene/Components/CharacterController.hpp>
#include <Workphone/Scene/Components/Component.hpp>
#include <Workphone/Scene/Components/ComponentEvent.hpp>
#include <Workphone/Scene/Components/ComponentEventListener.hpp>
#include <Workphone/Scene/Components/Constraint.hpp>
#include <Workphone/Scene/Components/Cubemap.hpp>
#include <Workphone/Scene/Components/Collision.hpp>
#include <Workphone/Scene/Components/CollisionBox.hpp>
#include <Workphone/Scene/Components/CollisionMesh.hpp>
#include <Workphone/Scene/Components/CollisionPlane.hpp>
#include <Workphone/Scene/Components/CollisionSphere.hpp>
#include <Workphone/Scene/Components/CollisionTerrain.hpp>
#include <Workphone/Scene/Components/FiniteStateMachine.hpp>
#include <Workphone/Scene/Components/Light.hpp>
#include <Workphone/Scene/Components/Material.hpp>
#include <Workphone/Scene/Components/Mesh.hpp>
#include <Workphone/Scene/Components/MeshRenderer.hpp>
#include <Workphone/Scene/Components/NetworkListener.hpp>
#include <Workphone/Scene/Components/NetworkPlayer.hpp>
#include <Workphone/Scene/Components/NetworkStream.hpp>
#include <Workphone/Scene/Components/NetworkView.hpp>
#include <Workphone/Scene/Components/ParticleSystem.hpp>
#include <Workphone/Scene/Components/LODGroup.hpp>
#include <Workphone/Scene/Components/Renderer.hpp>
#include <Workphone/Scene/Components/RenderTexture.hpp>
#include <Workphone/Scene/Components/Rigidbody.hpp>
#include <Workphone/Scene/Components/RigidbodyListener.hpp>
#include <Workphone/Scene/Components/Skybox.hpp>
#include <Workphone/Scene/Components/SkyboxPanorama.hpp>
#include <Workphone/Scene/Components/SubComponent.hpp>
#include <Workphone/Scene/Components/Script.hpp>
#include <Workphone/Scene/Components/VehicleController.hpp>
#include <Workphone/Scene/Components/VideoPlayer.hpp>
#include <Workphone/Scene/Components/WheelController.hpp>

#include <Workphone/Scene/Components/Camera/CameraController.hpp>
#include <Workphone/Scene/Components/Camera/CameraFollow.hpp>
#include <Workphone/Scene/Components/Camera/CameraTarget.hpp>
#include <Workphone/Scene/Components/Camera/FPSCameraController.hpp>
#include <Workphone/Scene/Components/Camera/EditorCameraController.hpp>
#include <Workphone/Scene/Components/Camera/SphericalCameraController.hpp>
#include <Workphone/Scene/Components/Camera/ThirdPersonCameraController.hpp>
#include <Workphone/Scene/Components/Camera/VehicleCameraController.hpp>

#include <Workphone/Scene/Components/Terrain/TerrainBlendMap.hpp>
#include <Workphone/Scene/Components/Terrain/TerrainGrassLayer.hpp>
#include <Workphone/Scene/Components/Terrain/TerrainLayer.hpp>
#include <Workphone/Scene/Components/Terrain/TerrainSystem.hpp>
#include <Workphone/Scene/Components/Terrain/TerrainTreeLayer.hpp>

#include <Workphone/Scene/Components/UI/Button.hpp>
#include <Workphone/Scene/Components/UI/Dropdown.hpp>
#include <Workphone/Scene/Components/UI/UIComponent.hpp>
#include <Workphone/Scene/Components/UI/Layout.hpp>
#include <Workphone/Scene/Components/UI/LayoutContainer.hpp>
#include <Workphone/Scene/Components/UI/Image.hpp>
#include <Workphone/Scene/Components/UI/InputField.hpp>
#include <Workphone/Scene/Components/UI/ScrollBar.hpp>
#include <Workphone/Scene/Components/UI/ScrollView.hpp>
#include <Workphone/Scene/Components/UI/Slider.hpp>
#include <Workphone/Scene/Components/UI/TabItem.hpp>
#include <Workphone/Scene/Components/UI/TableCell.hpp>
#include <Workphone/Scene/Components/UI/TableLayout.hpp>
#include <Workphone/Scene/Components/UI/TabPage.hpp>
#include <Workphone/Scene/Components/UI/TabView.hpp>
#include <Workphone/Scene/Components/UI/Text.hpp>
#include <Workphone/Scene/Components/UI/Thumbnail.hpp>
#include <Workphone/Scene/Components/UI/Toggle.hpp>
#include <Workphone/Scene/Components/UI/ToggleGroup.hpp>
#include <Workphone/Scene/Components/UI/ToolTip.hpp>
#include <Workphone/Scene/Components/UI/LayoutTransform.hpp>
#include <Workphone/Scene/Components/UI/GridLayout.hpp>
#include <Workphone/Scene/Components/UI/HorizontalLayout.hpp>
#include <Workphone/Scene/Components/UI/VerticalLayout.hpp>

#include <Workphone/Scene/Directors/ButtonDirector.hpp>
#include <Workphone/Scene/Directors/GraphicsSettingsDirector.hpp>
#include <Workphone/Scene/Directors/MaterialResourceDirector.hpp>
#include <Workphone/Scene/Directors/MeshResourceDirector.hpp>
#include <Workphone/Scene/Directors/PanelDirector.hpp>
#include <Workphone/Scene/Directors/LightingDirector.hpp>
#include <Workphone/Scene/Directors/SoundResourceDirector.hpp>
#include <Workphone/Scene/Directors/TextDirector.hpp>
#include <Workphone/Scene/Directors/TextureResourceDirector.hpp>
#include <Workphone/Scene/Directors/UiDialogDirector.hpp>
#include <Workphone/Scene/Directors/UiDirector.hpp>
#include <Workphone/Scene/Directors/UiElementDirector.hpp>

#include <Workphone/Scene/Systems/UI/LayoutTransformSystem.hpp>
#include <Workphone/Scene/Systems/LODSystem.hpp>

#include <Workphone/Scene/GameActor.hpp>
#include <Workphone/Scene/GameActorUtil.hpp>
#include <Workphone/Scene/CameraManager.hpp>
#include <Workphone/Scene/GameScene.hpp>
#include <Workphone/Scene/GameSceneBuilder.hpp>
#include <Workphone/Scene/GameManager.hpp>
#include <Workphone/Scene/Transform.hpp>
#include <Workphone/Scene/TransformSystem.hpp>
#include <Workphone/Scene/UiUtil.hpp>
#include <Workphone/Scene/GamePrefabManager.hpp>

// script
#include <Workphone/Script/ScriptEvent.hpp>
#include <Workphone/Script/ScriptClass.hpp>
#include <Workphone/Script/ScriptFunction.hpp>
#include <Workphone/Script/ScriptGenerator.hpp>
#include <Workphone/Script/ScriptInvoker.hpp>
#include <Workphone/Script/ScriptReceiverAdapter.hpp>
#include <Workphone/Script/ScriptVariable.hpp>

// state
#include <Workphone/State/Messages/StateFrameData.hpp>
#include <Workphone/State/Messages/StateMessage.hpp>
#include <Workphone/State/Messages/StateMessageAnimationEnable.hpp>
#include <Workphone/State/Messages/StateMessageBlendMapValue.hpp>
#include <Workphone/State/Messages/StateMessageBuffer.hpp>
#include <Workphone/State/Messages/StateMessageContact2.hpp>
#include <Workphone/State/Messages/StateMessageDefault.hpp>
#include <Workphone/State/Messages/StateMessageDirty.hpp>
#include <Workphone/State/Messages/StateMessageDrawLine.hpp>
#include <Workphone/State/Messages/StateMessageFloatValue.hpp>
#include <Workphone/State/Messages/StateMessageFragmentParam.hpp>
#include <Workphone/State/Messages/StateMessageIntValue.hpp>
#include <Workphone/State/Messages/StateMessageJobStatus.hpp>
#include <Workphone/State/Messages/StateMessageLoad.hpp>
#include <Workphone/State/Messages/StateMessageMaterial.hpp>
#include <Workphone/State/Messages/StateMessageMaterialName.hpp>
#include <Workphone/State/Messages/StateMessageObject.hpp>
#include <Workphone/State/Messages/StateMessageObjectsArray.hpp>
#include <Workphone/State/Messages/StateMessageOrientation.hpp>
#include <Workphone/State/Messages/StateMessagePair.hpp>
#include <Workphone/State/Messages/StateMessageParamVector4.hpp>
#include <Workphone/State/Messages/StateMessagePlay.hpp>
#include <Workphone/State/Messages/StateMessageProperties.hpp>
#include <Workphone/State/Messages/StateMessageSetTexture.hpp>
#include <Workphone/State/Messages/StateMessageSkyBox.hpp>
#include <Workphone/State/Messages/StateMessageStop.hpp>
#include <Workphone/State/Messages/StateMessageStringValue.hpp>
#include <Workphone/State/Messages/StateMessageText.hpp>
#include <Workphone/State/Messages/StateMessageTransform3.hpp>
#include <Workphone/State/Messages/StateMessageType.hpp>
#include <Workphone/State/Messages/StateMessageUIntValue.hpp>
#include <Workphone/State/Messages/StateMessageVector2.hpp>
#include <Workphone/State/Messages/StateMessageVector3.hpp>
#include <Workphone/State/Messages/StateMessageVector4.hpp>
#include <Workphone/State/Messages/StateMessageVisible.hpp>
#include <Workphone/State/Messages/StatePhysicsDynamicState2.hpp>
#include <Workphone/State/Messages/StatePhysicsForce2.hpp>
#include <Workphone/State/Messages/StatePhysicsPosition2.hpp>
#include <Workphone/State/Messages/StatePhysicsVelocity2.hpp>

#include <Workphone/State/States/AmbientLightStateData.hpp>
#include <Workphone/State/States/ApplicationStateData.hpp>
#include <Workphone/State/States/InputState.hpp>
#include <Workphone/State/States/BoundingBoxStateData.hpp>
#include <Workphone/State/States/BoxShapeStateData.hpp>
#include <Workphone/State/States/CameraStateData.hpp>
#include <Workphone/State/States/CompositorStateData.hpp>
#include <Workphone/State/States/ConstraintD6StateData.hpp>
#include <Workphone/State/States/ConstraintFixedStateData.hpp>
#include <Workphone/State/States/ConstraintStateData.hpp>
#include <Workphone/State/States/FlagsStateData.hpp>
#include <Workphone/State/States/FrustumStateData.hpp>
#include <Workphone/State/States/GraphicsMeshState.hpp>
#include <Workphone/State/States/GraphicsObjectData.hpp>
#include <Workphone/State/States/GraphicsSceneState.hpp>
#include <Workphone/State/States/LightStateData.hpp>
#include <Workphone/State/States/LightAttenuationStateData.hpp>
#include <Workphone/State/States/MaterialPassStateData.hpp>
#include <Workphone/State/States/MaterialStateData.hpp>
#include <Workphone/State/States/MaterialTechniqueStateData.hpp>
#include <Workphone/State/States/MaterialTextureStateData.hpp>
#include <Workphone/State/States/MeshShapeStateData.hpp>
#include <Workphone/State/States/PhysicsBodyMassState.hpp>
#include <Workphone/State/States/PhysicsBodyMotionState.hpp>
#include <Workphone/State/States/PhysicsBodyState.hpp>
#include <Workphone/State/States/PhysicsMaterialStateData.hpp>
#include <Workphone/State/States/PhysicsSceneState.hpp>
#include <Workphone/State/States/PlaneShapeState.hpp>
#include <Workphone/State/States/RenderTargetStateData.hpp>
#include <Workphone/State/States/RenderTextureState.hpp>
#include <Workphone/State/States/SceneNodeStateData.hpp>
#include <Workphone/State/States/State.hpp>
#include <Workphone/State/States/StateData.hpp>
#include <Workphone/State/States/ShapeStateData.hpp>
#include <Workphone/State/States/SkyStateData.hpp>
#include <Workphone/State/States/SoundManagerStateData.hpp>
#include <Workphone/State/States/SoundStateData.hpp>
#include <Workphone/State/States/SphereShapeStateData.hpp>
#include <Workphone/State/States/TerrainStateData.hpp>
#include <Workphone/State/States/TextureSamplerState.hpp>
#include <Workphone/State/States/TextureStateData.hpp>
#include <Workphone/State/States/UIAnchorStateData.hpp>
#include <Workphone/State/States/UIDragStateData.hpp>
#include <Workphone/State/States/UIDropdownStateData.hpp>
#include <Workphone/State/States/UIElementStateData.hpp>
#include <Workphone/State/States/UIImageStateData.hpp>
#include <Workphone/State/States/UILayoutStateData.hpp>
#include <Workphone/State/States/UIProgressBarStateData.hpp>
#include <Workphone/State/States/UISliderStateData.hpp>
#include <Workphone/State/States/UITextStateData.hpp>
#include <Workphone/State/States/UIToggleStateData.hpp>
#include <Workphone/State/States/UITransformStateData.hpp>
#include <Workphone/State/States/UIWindowStateData.hpp>
#include <Workphone/State/States/OverlayState.hpp>
#include <Workphone/State/States/OverlayContainerState.hpp>
#include <Workphone/State/States/OverlayElementState.hpp>
#include <Workphone/State/States/OverlayTextState.hpp>
#include <Workphone/State/States/VehicleStateData.hpp>
#include <Workphone/State/States/ViewportStateData.hpp>
#include <Workphone/State/States/WindowStateData.hpp>

// system
#include <Workphone/System/ApplicationManager.hpp>
#include <Workphone/System/CommandManager.hpp>
#include <Workphone/System/CommandManagerMT.hpp>
#include <Workphone/System/CompiledResource.hpp>
#include <Workphone/System/SelectionManager.hpp>
#include <Workphone/System/DebugUtil.hpp>
#include <Workphone/System/Director.hpp>
#include <Workphone/System/Factory.hpp>
#include <Workphone/System/FactoryTemplate.hpp>
#include <Workphone/System/FactoryManager.hpp>
#include <Workphone/System/FileSelection.hpp>
#include <Workphone/System/FrameStatistics.hpp>
#include <Workphone/System/FSMListener.hpp>
#include <Workphone/System/FSMManager.hpp>
#include <Workphone/System/Job.hpp>
#include <Workphone/System/JobQueue.hpp>
#include <Workphone/System/JobQueueMT.hpp>
#include <Workphone/System/JobCoroutine.hpp>
#include <Workphone/System/ScaleManipulator.hpp>
#include <Workphone/System/TranslateManipulator.hpp>
#include <Workphone/System/RotateManipulator.hpp>
#include <Workphone/System/RttiClassDefinition.hpp>
#include <Workphone/System/MessageBox.hpp>
#include <Workphone/System/PackageManager.hpp>
#include <Workphone/System/Plugin.hpp>
#include <Workphone/System/PluginManager.hpp>
#include <Workphone/System/ProjectManager.hpp>
#include <Workphone/System/ProcessManager.hpp>
#include <Workphone/System/Profile.hpp>
#include <Workphone/System/Profiler.hpp>
#include <Workphone/Interface/Resource/IResourceCompiler.hpp>
#include <Workphone/Interface/Resource/IResourceCompilerRegistry.hpp>
#include <Workphone/Interface/Resource/IResourceSystem.hpp>
#include <Workphone/System/ResourceCompilerRegistry.hpp>
#include <Workphone/System/ResourceID.hpp>
#include <Workphone/System/ResourceSystem.hpp>
#include <Workphone/System/StateContext.hpp>
#include <Workphone/System/StateQueue.hpp>
#include <Workphone/System/StateManager.hpp>
#include <Workphone/System/Task.hpp>
#include <Workphone/System/TaskManager.hpp>
#include <Workphone/System/ThreadPool.hpp>
#include <Workphone/System/TimerBoost.hpp>
#include <Workphone/System/TimerChrono.hpp>
#include <Workphone/System/TimerCPU.hpp>
#include <Workphone/System/TimerMT.hpp>
#include <Workphone/System/TimerWin32.hpp>
#include <Workphone/System/WaitForSeconds.hpp>
#include <Workphone/System/WindowMessageData.hpp>
#include <Workphone/System/WorkerThread.hpp>

#include <Workphone/Thread/RecursiveMutex.hpp>
#include <Workphone/Thread/SharedMutex.hpp>
#include <Workphone/Thread/SpinMutex.hpp>
#include <Workphone/Thread/SpinRWMutex.hpp>
#include <Workphone/Thread/Thread.hpp>
#include <Workphone/Thread/TryLockGuard.hpp>

#include <Workphone/UI/IconsFontAwesome6.h>

// vehicle
#include <Workphone/Vehicle/VehicleBody.hpp>
#include <Workphone/Vehicle/Vehicle.hpp>
#include <Workphone/Vehicle/VehicleManager.hpp>
#include <Workphone/Vehicle/WheelController.hpp>

#if defined WP_PLATFORM_APPLE
#    include <Workphone/Core/OSX/macUtils.hpp>
#endif


#include <Workphone/Interface/Procedural/IRoadSystem.hpp>
#include <Workphone/Interface/Procedural/ISkyAtmosphere.hpp>
#include <Workphone/Interface/Procedural/ITextureForge.hpp>
#include <Workphone/Interface/Procedural/IVehicleAppearance.hpp>
#include <Workphone/Interface/Procedural/IVehicleDamage.hpp>
#include <Workphone/Interface/Procedural/IVehicleDynamics.hpp>
#include <Workphone/Interface/Procedural/IVehicleEffects.hpp>
#include <Workphone/Interface/Procedural/IVehicleGenerator.hpp>
#include <Workphone/Interface/Procedural/IVehicleGeometry.hpp>
#include <Workphone/Interface/Procedural/IVehiclePhysics.hpp>
#include <Workphone/Interface/Procedural/IVehiclePresentation.hpp>

#include <Workphone/Scene/Components/ProceduralMeshComponent.hpp>
#include <Workphone/Scene/Components/ProceduralVehicle.hpp>
#include <Workphone/Scene/Components/ProceduralRaceScene.hpp>
#include <Workphone/Scene/Components/ProceduralRoad.hpp>
#include <Workphone/Scene/Components/ProceduralSky.hpp>
#include <Workphone/Scene/Components/ProceduralSurfaceTexture.hpp>

#endif  // __WP_CoreHeaders_h__
