project(WPAssimp)

add_compile_definitions (ASSIMP_BUILD_NO_OWN_ZLIB)
#add_compile_definitions (ASSIMP_USE_HUNTER)
add_compile_definitions (OPENDDL_STATIC_LIBARY)

add_compile_definitions (ASSIMP_BUILD_DRACO=0)

add_compile_definitions (ASSIMP_BUILD_NO_IFC_IMPORTER)
add_compile_definitions (ASSIMP_BUILD_NO_IFC_EXPORTER)
add_compile_definitions (ASSIMP_BUILD_NO_MD3_IMPORTER)
add_compile_definitions (ASSIMP_BUILD_NO_MD3_EXPORTER)
add_compile_definitions (ASSIMP_BUILD_NO_M3D_IMPORTER)
add_compile_definitions (ASSIMP_BUILD_NO_M3D_EXPORTER)
add_compile_definitions (WIN32_LEAN_AND_MEAN)
add_compile_definitions (UNICODE)
add_compile_definitions (_UNICODE)
add_compile_definitions (ASSIMP_BUILD_NO_C4D_IMPORTER)

add_compile_definitions (MINIZ_USE_UNALIGNED_LOADS_AND_STORES=0)
add_compile_definitions (ASSIMP_IMPORTER_GLTF_USE_OPEN3DGC=1)
add_compile_definitions (RAPIDJSON_HAS_STDSTRING=1)
add_compile_definitions (RAPIDJSON_NOMEMBERITERATORCLASS)
add_compile_definitions (ASSIMP_BUILD_DLL_EXPORT)
add_compile_definitions (_SCL_SECURE_NO_WARNINGS)
add_compile_definitions (_CRT_SECURE_NO_WARNINGS)
add_compile_definitions (OPENDDLPARSER_BUILD)

#add_compile_definitions (ASSIMP_BUILD_NO_GLTF_IMPORTER)
#add_compile_definitions (ASSIMP_BUILD_NO_GLTF2_IMPORTER)
#add_compile_definitions (ASSIMP_BUILD_NO_GLTF_EXPORTER)
#add_compile_definitions (ASSIMP_BUILD_NO_GLTF2_EXPORTER)

# define header and source files for the library
file(GLOB HEADER_FILES "../../Include/WPAssimp/*.h" "../../Include/WPAssimp/*.hpp")
file(GLOB SOURCE_FILES "../../Source/WPAssimp/*.h" "../../Source/WPAssimp/*.hpp" "../../Source/WPAssimp/*.cpp" "../../Source/WPAssimp/*.c" "../../Source/WPAssimp/*.cc" "../../Source/WPAssimp/*.mm")

set(WP_HEADER_REL_PATH "${WP_ROOT}/Engine/cpp/Project/WPAssimp/../../Include/WPAssimp")
set(WP_SOURCE_REL_PATH "${WP_ROOT}/Engine/cpp/Project/WPAssimp/../../Source/WPAssimp")

file(GLOB HEADER_FILES_SUBFOLDER "../../Include/WPAssimp/Extern/*.hpp")
file(GLOB SOURCE_FILES_SUBFOLDER "../../Source/WPAssimp/Extern/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_SUBFOLDER})
list(APPEND SOURCE_FILES ${SOURCE_FILES_SUBFOLDER})

file(GLOB_RECURSE HEADER_FILES_SUBFOLDER "../../Include/WPAssimp/Extern/assimp/*.h" "../../Include/WPAssimp/Extern/assimp/*.hpp")
file(GLOB_RECURSE SOURCE_FILES_SUBFOLDER "../../Source/WPAssimp/Extern/assimp/*.hpp" 
    "../../Source/WPAssimp/Extern/assimp/*.c" "../../Source/WPAssimp/Extern/assimp/*.cc" 
    "../../Source/WPAssimp/Extern/assimp/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_SUBFOLDER})
list(APPEND SOURCE_FILES ${SOURCE_FILES_SUBFOLDER})

file(GLOB_RECURSE HEADER_FILES_SUBFOLDER "../../Include/WPAssimp/Extern/contrib/Open3DGC/*.hpp")
file(GLOB_RECURSE SOURCE_FILES_SUBFOLDER "../../Source/WPAssimp/Extern/contrib/Open3DGC/*.hpp" "../../Source/WPAssimp/Extern/contrib/Open3DGC/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_SUBFOLDER})
list(APPEND SOURCE_FILES ${SOURCE_FILES_SUBFOLDER})

file(GLOB_RECURSE HEADER_FILES_SUBFOLDER "../../Include/WPAssimp/Extern/contrib/openddlparser/*.hpp")
file(GLOB_RECURSE SOURCE_FILES_SUBFOLDER "../../Source/WPAssimp/Extern/contrib/openddlparser/*.hpp" "../../Source/WPAssimp/Extern/contrib/openddlparser/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_SUBFOLDER})
list(APPEND SOURCE_FILES ${SOURCE_FILES_SUBFOLDER})

file(GLOB_RECURSE HEADER_FILES_SUBFOLDER "../../Include/WPAssimp/Extern/contrib/poly2tri/*.hpp")
file(GLOB_RECURSE SOURCE_FILES_SUBFOLDER "../../Source/WPAssimp/Extern/contrib/poly2tri/*.hpp" "../../Source/WPAssimp/Extern/contrib/poly2tri/*.c" 
    "../../Source/WPAssimp/Extern/contrib/poly2tri/*.cc" "../../Source/WPAssimp/Extern/contrib/poly2tri/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_SUBFOLDER})
list(APPEND SOURCE_FILES ${SOURCE_FILES_SUBFOLDER})

file(GLOB_RECURSE HEADER_FILES_SUBFOLDER "../../Include/WPAssimp/Extern/contrib/polyclipping/*.hpp")
file(GLOB_RECURSE SOURCE_FILES_SUBFOLDER "../../Source/WPAssimp/Extern/contrib/polyclipping/*.hpp" "../../Source/WPAssimp/Extern/contrib/polyclipping/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_SUBFOLDER})
list(APPEND SOURCE_FILES ${SOURCE_FILES_SUBFOLDER})

file(GLOB_RECURSE HEADER_FILES_SUBFOLDER "../../Include/WPAssimp/Extern/contrib/pugixml/*.hpp")
file(GLOB_RECURSE SOURCE_FILES_SUBFOLDER "../../Source/WPAssimp/Extern/contrib/pugixml/*.hpp" "../../Source/WPAssimp/Extern/contrib/pugixml/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_SUBFOLDER})
list(APPEND SOURCE_FILES ${SOURCE_FILES_SUBFOLDER})

file(GLOB_RECURSE HEADER_FILES_SUBFOLDER "../../Include/WPAssimp/Extern/contrib/zip/*.hpp")
file(GLOB_RECURSE SOURCE_FILES_SUBFOLDER "../../Source/WPAssimp/Extern/contrib/zip/*.hpp" "../../Source/WPAssimp/Extern/contrib/zip/*.c" "../../Source/WPAssimp/Extern/contrib/zip/*.cpp")
list(APPEND HEADER_FILES ${HEADER_FILES_SUBFOLDER})
list(APPEND SOURCE_FILES ${SOURCE_FILES_SUBFOLDER})

foreach(_source IN ITEMS ${HEADER_FILES})
    get_filename_component(_source_file_path "${_source}" DIRECTORY)
    string(REPLACE "${WP_HEADER_REL_PATH}" "" _group_file_path "${_source_file_path}")
    string(REPLACE "/" "\\" _group_file_path "${_group_file_path}")
    source_group("Header Files\\${_group_file_path}" FILES "${_source}")
endforeach()

foreach(_source IN ITEMS ${SOURCE_FILES})
    get_filename_component(_source_file_path "${_source}" DIRECTORY)
    string(REPLACE "${WP_SOURCE_REL_PATH}" "" _group_file_path "${_source_file_path}")
    string(REPLACE "/" "\\" _group_file_path "${_group_file_path}")
    source_group("Source Files\\${_group_file_path}" FILES "${_source}")
endforeach()

if (UNIX)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
endif()

include_directories( ${WP_ROOT}/Dependencies/boost )

if (WP_USE_ONETBB)
    include_directories( ${CMAKE_SOURCE_DIR}/Dependencies/onetbb/include )
elseif (WP_USE_TBB)
    include_directories( ${CMAKE_SOURCE_DIR}/Dependencies/tbb/include )
endif()

if (WP_USE_ASSET_IMPORT)
    #include_directories( ${WP_ROOT}/AdditionalLibraries/assimp/include )
    #include_directories( ${WP_ROOT}/AdditionalLibraries/assimp/include/vc142 )
endif()

include_directories( ${WP_ROOT}/Dependencies/tinybind )
include_directories( ${WP_ROOT}/Dependencies/tinyusdz/src )
include_directories( ${WP_ROOT}/Dependencies/tinyxml )
include_directories( ${WP_ROOT}/Dependencies/utf8/source )
include_directories( ${WP_ROOT}/Dependencies/zlib )
include_directories( ${WP_ROOT}/Dependencies/zziplib )
include_directories( ../../Include )
include_directories( "${WP_ROOT}/Engine/cpp/Include/WPAssimp/Extern/assimp" )
include_directories( "${WP_ROOT}/Engine/cpp/Include/WPAssimp/Extern/assimp/assimp" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/assimp" )

include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/draco/src" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/pugixml/src" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/pugixml/src" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/poly2tri" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/zlib/contrib" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/polyclipping" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/unzip" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/zip" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/zip/src" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/openddlparser/include" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern/contrib/zlib" )
include_directories( "${WP_ROOT}/Engine/cpp/Source/WPAssimp/Extern" )
include_directories( "${WP_ROOT}/Dependencies/rapidjson/include" )
include_directories( "${WP_ROOT}/Dependencies/rapidjson/include/rapidjson" )

if (WIN32)
    include_directories( "${WP_ROOT}/Engine/cpp/Include/WPAssimp/Extern/assimp/vc142" )
    include_directories( "${WP_ROOT}/Engine/cpp/Include/WPAssimp/Extern/assimp/vc142/assimp" )
elseif (APPLE)
    include_directories( "${WP_ROOT}/Engine/cpp/Include/WPAssimp/Extern/assimp/xcode" )
    include_directories( "${WP_ROOT}/Engine/cpp/Include/WPAssimp/Extern/assimp/xcode/assimp" )
elseif (UNIX)
    include_directories( "${WP_ROOT}/Engine/cpp/Include/WPAssimp/Extern/assimp/linux" )
    include_directories( "${WP_ROOT}/Engine/cpp/Include/WPAssimp/Extern/assimp/linux/assimp" )
endif()

if (WP_USE_PRECOMPILED_HEADERS)
    wp_use_precompiled_header(WPAssimp "WPAssimp/WPAssimpPCH.hpp" "${CMAKE_SOURCE_DIR}/Engine/cpp/Source/WPAssimp/WPAssimpPCH.cpp")

    file(GLOB_RECURSE OGRE_SOURCE_FILES "${CMAKE_SOURCE_DIR}/Engine/cpp/Source/WPAssimp/Extern/*.cpp")
    set_source_files_properties(${OGRE_SOURCE_FILES} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)

        file(GLOB_RECURSE OGRE_SOURCE_FILES "${CMAKE_SOURCE_DIR}/Engine/cpp/Source/WPAssimp/Extern/*.cc")
    set_source_files_properties(${OGRE_SOURCE_FILES} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)

    file(GLOB_RECURSE OGRE_SOURCE_FILES "${CMAKE_SOURCE_DIR}/Engine/cpp/Source/WPAssimp/Extern/*.c")
    set_source_files_properties(${OGRE_SOURCE_FILES} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)
endif()

if (NOT WP_STATIC_LIB)
    if (WIN32)
        link_directories(WPAssimp ${CMAKE_SOURCE_DIR}/libs/windows/${WP_TOOLSET}/${WP_ARCH}/${WP_STATIC_LINK_CRT_TYPE}/${CMAKE_BUILD_TYPE})
    endif()
endif()

if (WP_STATIC_LIB)
    add_library(WPAssimp STATIC ${HEADER_FILES} ${SOURCE_FILES})
else ()
    add_library(WPAssimp SHARED ${HEADER_FILES} ${SOURCE_FILES})
endif()

if (NOT WP_STATIC_LIB)
    if (WIN32)
        target_link_libraries(WPAssimp Workphone.lib)
        target_link_libraries(WPAssimp tinyusdz_static.lib)

        if (WP_USE_ONETBB)
            target_link_libraries(WPAssimp debug tbb12_debug.lib optimized tbb12.lib)
            target_link_libraries(WPAssimp debug tbbmalloc_debug.lib optimized tbbmalloc.lib)
            target_link_libraries(WPAssimp debug tbbmalloc_proxy_debug.lib optimized tbbmalloc_proxy.lib)
        elseif (WP_USE_TBB)
            if (WP_TBB_BUILD_STATIC)
                target_link_libraries(WPAssimp tbb_static.lib)
                target_link_libraries(WPAssimp tbbmalloc_static.lib)
            else()
                target_link_libraries(WPAssimp tbb.lib)
			    target_link_libraries(WPAssimp tbbmalloc.lib)
            endif()
        endif()

        target_link_libraries(WPAssimp minizip.lib)
        target_link_libraries(WPAssimp zlib.lib)
        target_link_libraries(WPAssimp zzip.lib)
    elseif (APPLE)
        target_link_libraries(WPAssimp libWorkphone.a)
    elseif (UNIX)
        target_link_libraries(WPAssimp -Wl,--start-group Workphone.a 
                -Wl,--end-group )

        target_link_libraries(WPAssimp ${X11_LIBRARIES})
        target_link_libraries(WPAssimp ${CMAKE_THREAD_LIBS_INIT} )
        target_link_libraries(WPAssimp ${CMAKE_DL_LIBS})
    endif ()
endif()

set_target_properties (WPAssimp PROPERTIES FOLDER Engine/Cpp/Render)

if (NOT WP_STATIC_LIB)
	target_compile_definitions(WPAssimp PUBLIC WPAssimp_EXPORTS)
endif()

if (NOT WP_STATIC_LIB)
    add_dependencies(WPAssimp Workphone)
endif()
