if (WIN32)
    file(GLOB_RECURSE HEADER_FILES "${WP_ROOT}/Engine/cpp/Include/Workphone/*.hpp" "${WP_ROOT}/Engine/cpp/Include/Workphone/*.h" "${WP_ROOT}/Engine/cpp/Include/Workphone/*.inl")
    file(GLOB_RECURSE SOURCE_FILES "${WP_ROOT}/Engine/cpp/Source/Workphone/*.cpp" "${WP_ROOT}/Engine/cpp/Source/Workphone/*.c")
elseif(APPLE)
    file(GLOB_RECURSE HEADER_FILES "${WP_ROOT}/Engine/cpp/Include/Workphone/*.hpp" "${WP_ROOT}/Engine/cpp/Include/Workphone/*.h" "${WP_ROOT}/Engine/cpp/Include/Workphone/*.inl")
    file(GLOB_RECURSE SOURCE_FILES "${WP_ROOT}/Engine/cpp/Source/Workphone/*.cpp" "${WP_ROOT}/Engine/cpp/Source/Workphone/*.c" "${WP_ROOT}/Engine/cpp/Source/Workphone/*.mm")
else()
    file(GLOB_RECURSE HEADER_FILES "${WP_ROOT}/Engine/cpp/Include/Workphone/*.hpp" "${WP_ROOT}/Engine/cpp/Include/Workphone/*.h" "${WP_ROOT}/Engine/cpp/Include/Workphone/*.inl")
    file(GLOB_RECURSE SOURCE_FILES "${WP_ROOT}/Engine/cpp/Source/Workphone/*.cpp" "${WP_ROOT}/Engine/cpp/Source/Workphone/*.c")
endif()

if (NOT WP_BUILD_RESOURCE_SYSTEM)
    set(_RESOURCE_SYSTEM_FILES
        CompiledResource
        ResourceCompiler
        ResourceCompilerRegistry
        ResourceID
        ResourceSystem)
    foreach(_resource_file IN LISTS _RESOURCE_SYSTEM_FILES)
        list(FILTER HEADER_FILES EXCLUDE REGEX "/System/${_resource_file}\\.(h|hpp|inl)$")
        list(FILTER SOURCE_FILES EXCLUDE REGEX "/System/${_resource_file}\\.(c|cpp|mm)$")
    endforeach()
endif()

set(WP_HEADER_REL_PATH "${WP_ROOT}/Engine/cpp/Include/Workphone")
set(WP_SOURCE_REL_PATH "${WP_ROOT}/Engine/cpp/Source/Workphone")

add_compile_definitions (PXR_USE_NAMESPACES=0)
add_compile_definitions (PXR_STATIC=1)
add_compile_definitions (ENABLE_PTR_RTTI=0)
add_compile_definitions (YAML_CPP_STATIC_DEFINE)
add_compile_definitions (WP_GARBAGE_COLLECTED=0)

foreach(_source IN ITEMS ${HEADER_FILES})
    get_filename_component(_source_file_path "${_source}" DIRECTORY)
    string(REPLACE "${WP_HEADER_REL_PATH}" "" _group_file_path "${_source_file_path}")
    string(REPLACE "\\" "/" _group_file_path "${_group_file_path}")
    source_group("Header Files\\${_group_file_path}" FILES "${_source}")
endforeach()

foreach(_source IN ITEMS ${SOURCE_FILES})
    get_filename_component(_source_file_path "${_source}" DIRECTORY)
    string(REPLACE "${WP_SOURCE_REL_PATH}" "" _group_file_path "${_source_file_path}")
    string(REPLACE "/" "\\" _group_file_path "${_group_file_path}")
    source_group("Source Files\\${_group_file_path}" FILES "${_source}")
endforeach()

if (UNIX)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
endif()

include_directories( ${CMAKE_SOURCE_DIR}/Dependencies )
include_directories( ${CMAKE_SOURCE_DIR}/Dependencies/boost )

if (WP_USE_ONETBB)
    include_directories( ${CMAKE_SOURCE_DIR}/Dependencies/onetbb/include )
elseif (WP_USE_TBB)
    include_directories( ${CMAKE_SOURCE_DIR}/Dependencies/tbb/include )
endif()

include_directories( ${WP_ROOT}/Dependencies/nativefiledialog/include )

if (WP_USE_NGPLANT)
    include_directories( ${WP_ROOT}/Dependencies/ngplant )
endif()

include_directories( ${WP_ROOT}/Dependencies/openusd )
include_directories( ${WP_ROOT}/Dependencies/openusd/include )
include_directories( ${WP_ROOT}/Dependencies/openusd/include/pxr )
include_directories( ${WP_ROOT}/Dependencies/pugixml/src )
include_directories( ${WP_ROOT}/Dependencies/tinyxml )
include_directories( ${WP_ROOT}/Dependencies/cJSON )
include_directories( ${WP_ROOT}/Dependencies/utf8/source )
include_directories( ${WP_ROOT}/Dependencies/yaml-cpp/include )
include_directories( ${WP_ROOT}/Dependencies/minizip/include )
include_directories( ${WP_ROOT}/Dependencies/zlib/include )
include_directories( ${WP_ROOT}/Dependencies/zzip/include )
include_directories( ${WP_ROOT}/Engine/cpp/Include )

if (WP_BUILD_FILEWATCHER)
    include_directories( ${WP_ROOT}/Dependencies/simplefilewatcher/includes )
endif()

if(APPLE)
    set(CMAKE_MACOSX_RPATH 1)
    find_library(COCOA_LIBRARY Cocoa)
    find_library(FOUNDATION_LIBRARY Foundation)
    find_library(IOKIT_LIBRARY IOKit)
    find_path(COCOA_INCLUDE_DIR Cocoa/Cocoa.hpp)
    find_library(CARBON_LIBRARY Carbon)

    #add_definitions(-x objective-c++)
endif()

if (WP_USE_PRECOMPILED_HEADERS)
    wp_use_precompiled_header(Workphone "Workphone/WorkphonePCH.hpp" "${CMAKE_SOURCE_DIR}/Engine/cpp/Source/Workphone/WorkphonePCH.cpp")

    file(GLOB_RECURSE OGRE_SOURCE_FILES "${CMAKE_SOURCE_DIR}/Engine/cpp/Source/Workphone/Extern/*.cpp")
    set_source_files_properties(${OGRE_SOURCE_FILES} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)

    file(GLOB_RECURSE OGRE_SOURCE_FILES "${CMAKE_SOURCE_DIR}/Engine/cpp/Source/Workphone/Extern/*.c")
    set_source_files_properties(${OGRE_SOURCE_FILES} PROPERTIES SKIP_PRECOMPILE_HEADERS ON)
endif()

if (NOT WP_STATIC_LIB)
    if (WIN32)
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/libs/windows/${WP_TOOLSET}/${WP_ARCH}/${WP_STATIC_LINK_CRT_TYPE}/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/windows/${WP_TOOLSET}/${WP_ARCH}/${WP_STATIC_LINK_CRT_TYPE}/tbb/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/windows/boost/${CMAKE_BUILD_TYPE})
    elseif (APPLE)
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/libs/macOS/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/macOS)

        link_directories(Workphone ${WP_ROOT}/Dependencies/lib/macOS/boost)
        link_directories(Workphone ${WP_ROOT}/Dependencies/lib/macOS/boost/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/macOS/tbb/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS)
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/${CMAKE_BUILD_TYPE})

        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/assimp/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/physx/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/wildmagic/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/${CMAKE_BUILD_TYPE})

        if (WP_GRAPHICS_SYSTEM_OGRENEXT)
            link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/ogrenext/${CMAKE_BUILD_TYPE})
            link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/ogrenext/dependencies/lib/${CMAKE_BUILD_TYPE})
        elseif (WP_GRAPHICS_SYSTEM_OGRE)
            link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/ogre/)
            link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/macOS/ogre/dependencies/lib/)
            link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/directx/Lib/x64)
        endif ()
    elseif (UNIX)
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/libs/linux/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/linux)
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/linux/boost)
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/linux/boost/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/linux/boost/${WP_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/Dependencies/lib/linux/tbb)
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/linux)
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/linux/physx/${CMAKE_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/linux/physx/${WP_BUILD_TYPE})
        link_directories(Workphone ${CMAKE_SOURCE_DIR}/AdditionalLibraries/lib/linux/wildmagic)
    endif ()
endif ()

if (WP_STATIC_LIB)
    add_library(Workphone STATIC ${HEADER_FILES} ${SOURCE_FILES})
else ()
    add_library(Workphone SHARED ${HEADER_FILES} ${SOURCE_FILES})
endif()

target_include_directories(Workphone PUBLIC
    ${WP_ROOT}/Engine/cpp/Include
    ${CMAKE_SOURCE_DIR}/Dependencies/boost
)

if (NOT WP_STATIC_LIB)
    if (WIN32)
        if (WP_USE_ONETBB)
            target_link_libraries(Workphone debug tbb12_debug.lib optimized tbb12.lib)
            target_link_libraries(Workphone debug tbbmalloc_debug.lib optimized tbbmalloc.lib)
            target_link_libraries(Workphone debug tbbmalloc_proxy_debug.lib optimized tbbmalloc_proxy.lib)
        elseif (WP_USE_TBB)
            if (WP_TBB_BUILD_STATIC)
                target_link_libraries(Workphone tbb_static.lib)
                target_link_libraries(Workphone tbbmalloc_static.lib)
            else()
                target_link_libraries(Workphone tbb.lib)
			    target_link_libraries(Workphone tbbmalloc.lib)
            endif()
        endif()

        if (WP_ENABLE_BOOST)
            target_link_libraries(Workphone Shlwapi)
            target_link_libraries(Workphone Dbghelp)

            target_link_libraries(Workphone bcrypt.lib)
            target_link_libraries(Workphone libboost_thread.lib)
            target_link_libraries(Workphone libboost_date_time.lib)
            target_link_libraries(Workphone libboost_chrono.lib)
            target_link_libraries(Workphone libboost_context.lib)
            target_link_libraries(Workphone libboost_timer.lib)
            target_link_libraries(Workphone libboost_filesystem.lib)
            target_link_libraries(Workphone libboost_json.lib)
        endif()

        if (WP_ENABLE_USD)
            target_link_libraries(Workphone usd_usd.lib)
            target_link_libraries(Workphone usd_ar.lib)
            target_link_libraries(Workphone usd_arch.lib)
            target_link_libraries(Workphone usd_sdf.lib)
            target_link_libraries(Workphone usd_sdr.lib)
            target_link_libraries(Workphone usd_tf.lib)

            target_link_libraries(Workphone usd_usdGeom.lib)
            target_link_libraries(Workphone usd_usdUtils.lib)
        endif()

        target_link_libraries(Workphone minizip.lib)
        target_link_libraries(Workphone nativefiledialog.lib)

        if (WP_USE_NGPLANT)
            target_link_libraries(Workphone ngcore.lib)
        endif()
        
        target_link_libraries(Workphone opcode.lib)
        target_link_libraries(Workphone pugixml.lib)
        target_link_libraries(Workphone simplefilewatcher.lib) 
        target_link_libraries(Workphone tinyxml.lib)   
        target_link_libraries(Workphone yaml-cpp.lib)
        target_link_libraries(Workphone zlib.lib)
        target_link_libraries(Workphone zzip.lib)
    elseif (APPLE)
        target_link_libraries(Workphone libboost_thread.a)
        target_link_libraries(Workphone libboost_date_time.a)
        target_link_libraries(Workphone libboost_chrono.a)
        target_link_libraries(Workphone libboost_timer.a)
        target_link_libraries(Workphone libboost_filesystem.a)
        target_link_libraries(Workphone libboost_json.a)

        if (WP_USE_TBB)
            if (WP_TBB_BUILD_STATIC)
                target_link_libraries(Workphone tbb_static.a)
                target_link_libraries(Workphone tbbmalloc_static.a)
            else()
                target_link_libraries(Workphone libtbb.a)
                target_link_libraries(Workphone libtbbmalloc.a)
            endif()
        endif()

        target_link_libraries(Workphone minizip.a)
        target_link_libraries(Workphone nativefiledialog.a)
        target_link_libraries(Workphone opcode.a)
        target_link_libraries(Workphone pugixml.a)
        target_link_libraries(Workphone rttr.a)
        target_link_libraries(Workphone simplefilewatcher.a)
        target_link_libraries(Workphone tinyxml.a)
        target_link_libraries(Workphone yaml-cpp.a)
        target_link_libraries(Workphone zlib.a)
        target_link_libraries(Workphone zzip.a)

        target_link_libraries(Workphone stdc++ "-framework AppKit" "-framework Metal" "-framework MetalKit" "-framework OpenGL" "-framework Foundation" "-framework QuartzCore" "-framework CoreGraphics" "-framework CoreServices" "-framework Cocoa" "-framework Carbon" "-framework IOKit" "-framework GameController" objc)
        set_target_properties(Workphone PROPERTIES LINK_FLAGS "-Wl,-F/Library/Frameworks")
    elseif (UNIX)
        target_link_libraries(Workphone -Wl,--start-group Workphone.a WPVehiclePhysics.a libWPProcedural.a WPImGui.a
            FBMath.a FBMesh.a WPOISInput.a WPVehiclePhysics.a FBData.a FBState.a libWPPhysx.a libWPSQLite.a
            libWPVehiclePhysics.a FBGraphics.a WPGraphicsOgreNext.a WPAssimp.a FBRenderUI.a libFBCPlusPlus.a
            libboost_thread-gcc5-mt-s-x64-1_70.a
            libboost_date_time-gcc5-mt-s-x64-1_70.a
            libboost_chrono-gcc5-mt-s-x64-1_70.a
            libboost_timer-gcc5-mt-s-x64-1_70.a
            libboost_filesystem-gcc5-mt-s-x64-1_70.a
            debug libtbb_debug.a optimized libtbb.a
            debug libtbbmalloc_debug.a optimized libtbbmalloc.a
            libWm5Core.a libWm5Mathematics.a
            libLowLevel.a libLowLevelCloth.a libPhysXProfileSDK.a libPhysX3Common.a libSceneQuery.a 
            libSimulationController.a libPhysX3Cooking.a libPhysX3Extensions.a libPhysX3.a libPhysX3Vehicle.a libPxTask.a
            -Wl,--end-group )

        if (WP_GRAPHICS_SYSTEM_OGRENEXT)
            target_link_libraries(Workphone WPGraphicsOgreNext.a)
            target_link_libraries(Workphone freetype.a)
        elseif(WP_GRAPHICS_SYSTEM_SOFTWARE)
            target_link_libraries(Workphone libFBGraphicsSoftware.a)
        endif()

        target_link_libraries(Workphone png)
        target_link_libraries(Workphone Xaw)
        target_link_libraries(Workphone Xrandr)
        target_link_libraries(Workphone Xt)
        target_link_libraries(Workphone xcb)
        target_link_libraries(Workphone GL)
        target_link_libraries(Workphone ${X11_LIBRARIES})
        target_link_libraries(Workphone ${CMAKE_THREAD_LIBS_INIT} )
        target_link_libraries(Workphone ${CMAKE_DL_LIBS})
    endif ()
endif ()

set_target_properties (Workphone PROPERTIES FOLDER Engine/Cpp)

if (NOT WP_STATIC_LIB)
	target_compile_definitions(Workphone PRIVATE WPCore_EXPORTS)
endif()

if (WP_BUILD_DEPENDENCIES)
	if (NOT WP_STATIC_LIB)
		add_dependencies(Workphone boost_thread)
		add_dependencies(Workphone boost_date_time)
		add_dependencies(Workphone boost_chrono)
		add_dependencies(Workphone boost_context)
		add_dependencies(Workphone boost_timer)
		add_dependencies(Workphone boost_filesystem)
		add_dependencies(Workphone boost_json)
		add_dependencies(Workphone pugixml-static)
		add_dependencies(Workphone minizip)
		add_dependencies(Workphone nativefiledialog)

		if (WP_USE_NGPLANT)
			add_dependencies(Workphone ngcore)
		endif()

		add_dependencies(Workphone rttr)
		add_dependencies(Workphone simplefilewatcher) 
		add_dependencies(Workphone tinyusdz_static)
		add_dependencies(Workphone tinyxml) 
		#add_dependencies(Workphone tinyxmlstatic) 
		add_dependencies(Workphone sdr) 
		add_dependencies(Workphone usd) 
		add_dependencies(Workphone usdGeom) 
		add_dependencies(Workphone usdUtils) 
		add_dependencies(Workphone yaml-cpp)
		add_dependencies(Workphone zlib)
		add_dependencies(Workphone zzip)

		if (WP_USE_OPCODE_LIB) 
			add_dependencies(Workphone opcode)
		endif()

		if (WP_USE_TBB)
			if (WP_TBB_BUILD_STATIC)
				add_dependencies(Workphone tbb_static)
				add_dependencies(Workphone tbbmalloc_static)
			else()
				add_dependencies(Workphone tbb)
				add_dependencies(Workphone tbbmalloc)
			endif()
		endif()
	endif()
endif()
