set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/CMake")
include(cpp_defines)
include(cpp_compiler_options)

if (WIN32)
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${WP_ROOT}/libs/windows/${WP_TOOLSET}/${WP_ARCH}/${WP_STATIC_LINK_CRT_TYPE}/${CMAKE_BUILD_TYPE})
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${WP_ROOT}/libs/windows/${WP_TOOLSET}/${WP_ARCH}/${WP_STATIC_LINK_CRT_TYPE}/${CMAKE_BUILD_TYPE})
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${WP_ROOT}/bin/windows/${WP_TOOLSET}/${WP_ARCH}/${WP_STATIC_LINK_CRT_TYPE}/${CMAKE_BUILD_TYPE})
elseif (ANDROID)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${WP_ROOT}/libs/android/${ANDROID_ABI}/${CMAKE_BUILD_TYPE})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${WP_ROOT}/libs/android/${ANDROID_ABI}/${CMAKE_BUILD_TYPE})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${WP_ROOT}/bin/android/${ANDROID_ABI}/${CMAKE_BUILD_TYPE})
elseif (APPLE_IOS)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${WP_ROOT}/libs/iOS/${WP_TARGET_ARCH}/${CMAKE_BUILD_TYPE})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${WP_ROOT}/libs/iOS/${WP_TARGET_ARCH}/${CMAKE_BUILD_TYPE})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${WP_ROOT}/bin/iOS/${WP_TARGET_ARCH}/${CMAKE_BUILD_TYPE})
elseif (APPLE)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${WP_ROOT}/libs/macOS/${CMAKE_BUILD_TYPE})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${WP_ROOT}/libs/macOS/${CMAKE_BUILD_TYPE})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${WP_ROOT}/bin/macOS/${CMAKE_BUILD_TYPE})
elseif (UNIX)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${WP_ROOT}/libs/linux/${CMAKE_BUILD_TYPE})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${WP_ROOT}/libs/linux/${CMAKE_BUILD_TYPE})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${WP_ROOT}/bin/linux/${CMAKE_BUILD_TYPE})
endif (WIN32)

add_compile_definitions (PX_PHYSX_STATIC_LIB)
add_compile_definitions (PX_PHYSX_CORE_STATIC_LIB)
add_compile_definitions (PX_FOUNDATION_NO_EXPORTS)
add_compile_definitions (PX_COOKING)
#add_compile_definitions (PX_CALL_CONV)
add_compile_definitions (PXR_STATIC=1)

if (APPLE)
	#add_compile_definitions(__MATH_H__)
endif ()

if(WP_BUILD_PHYSICS_DEBUG)
	add_compile_definitions(
		$<$<CONFIG:Debug>:PX_SUPPORT_VISUAL_DEBUGGER>
	)
	
	add_compile_definitions(
		$<$<CONFIG:Debug>:PX_DEBUG>
	)
	
	add_compile_definitions(
		$<$<CONFIG:Debug>:PX_CHECKED>
	)
	
	add_compile_definitions(
		$<$<CONFIG:Debug>:PX_NVTX>
	)
endif()

# Set the BOOST_INSTALL_LAYOUT
set(BOOST_INSTALL_LAYOUT "SYSTEM" CACHE STRING "Boost install layout")
	
add_subdirectory(boost)
add_subdirectory(box2d)
#add_subdirectory(bgfx)
add_subdirectory(cppsqlite)
add_subdirectory(FreeImage)
add_subdirectory(freetype)
#add_subdirectory(freetype2)
add_subdirectory(lua)
add_subdirectory(lua_cjson)
add_subdirectory(luabind)
add_subdirectory(imgui)
add_subdirectory(impact)
#add_subdirectory(irrlicht)
add_subdirectory(minizip)
add_subdirectory(nativefiledialog)
add_subdirectory(ngplant)
#add_subdirectory(ogre-next)
add_subdirectory(ois)
add_subdirectory(openusd)
add_subdirectory(opcode)
add_subdirectory(pugixml)
add_subdirectory(physx)
add_subdirectory(rttr)
add_subdirectory(simplefilewatcher)
add_subdirectory(sqlite)
add_subdirectory(tinybind)
add_subdirectory(tinyxml)
add_subdirectory(tinyxml2)
add_subdirectory(tinyusdz)
add_subdirectory(tbb)

if (WP_BUILD_WXWIDGETS)
	add_subdirectory(wxwidgets)
endif()

add_subdirectory(yaml-cpp)
add_subdirectory(zlib)
add_subdirectory(zzip)

add_subdirectory( icu )
add_subdirectory( harfbuzz )
add_subdirectory( sds_library )

set_target_properties (box2d PROPERTIES FOLDER Dependencies/box2d)

#set_target_properties (bgfx PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (bx PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (bimg PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (astc PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (astc-codec PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (edtaa3 PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (etc1 PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (etc2 PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (iqa PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (nvtt PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (pvrtc PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (squish PROPERTIES FOLDER Dependencies/bgfx)
#set_target_properties (tinyexr PROPERTIES FOLDER Dependencies/bgfx)

set_target_properties (boost_assert PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_atomic PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_chrono PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_container PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_context PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_contract PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_core PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_coroutine PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_date_time PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_exception PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_fiber PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_fiber_numa PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_filesystem PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_graph PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_iostreams PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_json PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_locale PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_log PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_nowide PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_prg_exec_monitor PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_program_options PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_log_setup PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_random PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_serialization PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_stacktrace_basic PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_stacktrace_noop PROPERTIES FOLDER Dependencies/boost)

if (WIN32)
	set_target_properties (boost_stacktrace_windbg PROPERTIES FOLDER Dependencies/boost)
	set_target_properties (boost_stacktrace_windbg_cached PROPERTIES FOLDER Dependencies/boost)
endif()

set_target_properties (boost_system PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_test_exec_monitor PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_thread PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_timer PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_type_erasure PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_unit_test_framework PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_url PROPERTIES FOLDER Dependencies/boost)

set_target_properties (boost_variant2 PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_wave PROPERTIES FOLDER Dependencies/boost)
set_target_properties (boost_wserialization PROPERTIES FOLDER Dependencies/boost)

set_target_properties (FreeImage PROPERTIES FOLDER Dependencies/FreeImage)
set_target_properties (freetype PROPERTIES FOLDER Dependencies/freetype)
#set_target_properties (freetype2 PROPERTIES FOLDER Dependencies/freetype)

#set_target_properties (irrlicht PROPERTIES FOLDER Dependencies/irrlicht)
#set_target_properties (GUIEditor PROPERTIES FOLDER Dependencies/irrlicht)

set_target_properties (minizip PROPERTIES FOLDER Dependencies/minizip)
set_target_properties (nativefiledialog PROPERTIES FOLDER Dependencies/nativefiledialog)

set_target_properties (ngcore PROPERTIES FOLDER Dependencies/ngplant)
#set_target_properties (ngplant PROPERTIES FOLDER Dependencies/ngplant)

#set_target_properties (OgreNextAtmosphere PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (OgreCmgenToCubemap PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (OgreNextHlmsUnlit PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (OgreNextHlmsPbs PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (OgreNextMeshLodGenerator PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (OgreNextOverlay PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (OgreNextProperty PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (Plugin_ParticleFX PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (Plugin_ParticleFX2 PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (RenderSystem_Direct3D11 PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (RenderSystem_GL3Plus PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (RenderSystem_NULL PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (OgreNextMain PROPERTIES FOLDER Dependencies/ogre-next)
#set_target_properties (OgreMeshTool PROPERTIES FOLDER Dependencies/ogre-next)

set_target_properties (OIS PROPERTIES FOLDER Dependencies/ois)
set_target_properties (FFConsoleApp PROPERTIES FOLDER Dependencies/ois)
set_target_properties (ConsoleApp PROPERTIES FOLDER Dependencies/ois)

set_target_properties (opcode PROPERTIES FOLDER Dependencies/opcode)

set_target_properties (PhysX3 PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysX3Extensions PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysX3Common PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysX3Cooking PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysX3Vehicle PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysXProfileSDK PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysXVisualDebuggerSDK PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PxTask PROPERTIES FOLDER Dependencies/physx)

if (WIN32)
	set_target_properties (PvdRuntime PROPERTIES FOLDER Dependencies/physx)
endif()

set_target_properties (PhysX3Foundation PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysX3LowLevel PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysX3LowLevelCloth PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PhysX3MetaData PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PxSceneQuery PROPERTIES FOLDER Dependencies/physx)
set_target_properties (PxSimulationController PROPERTIES FOLDER Dependencies/physx)

set_target_properties (rttr PROPERTIES FOLDER Dependencies/rttr)
set_target_properties (tinyxml PROPERTIES FOLDER Dependencies/tinyxml)
set_target_properties (tinyxml2 PROPERTIES FOLDER Dependencies/tinyxml2)
set_target_properties( tbb tbb_def_files  tbbmalloc  tbbmalloc_proxy  PROPERTIES FOLDER Dependencies/tbb )

if (WP_TBB_BUILD_STATIC)
	set_target_properties( tbb_static tbb_def_files tbbmalloc_static tbbmalloc_proxy_static PROPERTIES FOLDER Dependencies/tbb )
endif()

set_target_properties (yaml-cpp PROPERTIES FOLDER Dependencies/yaml-cpp)
set_target_properties (zlib PROPERTIES FOLDER Dependencies/zlib)
set_target_properties (zzip PROPERTIES FOLDER Dependencies/zzip)

set_target_properties (lua PROPERTIES FOLDER Dependencies/lua)
set_target_properties (luavm PROPERTIES FOLDER Dependencies/lua)
set_target_properties (lua_cjson PROPERTIES FOLDER Dependencies/lua)
set_target_properties (luabind PROPERTIES FOLDER Dependencies/lua)

set_target_properties (imgui PROPERTIES FOLDER Dependencies/imgui)
set_target_properties (impact PROPERTIES FOLDER Dependencies/impact)
set_target_properties (simplefilewatcher PROPERTIES FOLDER Dependencies/simplefilewatcher)

set_target_properties (icucommon PROPERTIES FOLDER Dependencies/icu)
set_target_properties (sds_library PROPERTIES FOLDER Dependencies/sds_library)
set_target_properties (harfbuzz PROPERTIES FOLDER Dependencies/harfbuzz)
set_target_properties (harfbuzz-subset PROPERTIES FOLDER Dependencies/harfbuzz)

set_target_properties (pugixml-static PROPERTIES FOLDER Dependencies/pugixml)
set_target_properties (tinyusdz_static PROPERTIES FOLDER Dependencies/tinyusdz)

set_target_properties (arch_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (ar_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (gf_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (js_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (pegtl_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (plug_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (tf_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (trace_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (ts_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (vt_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (work_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (kind_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (ndr_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (pcp_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (sdf_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (sdr_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usd_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdGeom_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdHydra_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdLux_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdMedia_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdPhysics_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdProc_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdRender_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdRi_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdSemantics_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdShade_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdSkel_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdUI_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdUtils_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)
set_target_properties (usdVol_headerfiles PROPERTIES FOLDER Dependencies/pxr/headerfiles)

set_target_properties (arch PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (ar PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (gf PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (js PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (pegtl PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (plug PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (tf PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (trace PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (ts PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (vt PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (work PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (kind PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (ndr PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (pcp PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (sdf PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (sdr PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usd PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdGeom PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdHydra PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdLux PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdMedia PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdPhysics PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdProc PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdRender PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdRi PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdSemantics PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdShade PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdSkel PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdUI PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdUtils PROPERTIES FOLDER Dependencies/pxr)
set_target_properties (usdVol PROPERTIES FOLDER Dependencies/pxr)

set_target_properties (cppsqlite PROPERTIES FOLDER Dependencies/cppsqlite)
set_target_properties (sqlite PROPERTIES FOLDER Dependencies/sqlite)
set_target_properties (tinybind PROPERTIES FOLDER Dependencies/tinybind)
