#ifndef WPGStreamer_h__
#define WPGStreamer_h__



#include "WorkphoneAutolink.hpp"



#ifdef _DEBUG
	#pragma comment(lib, "WPGStreamer_d.lib")

#pragma comment(lib, "atk-1.0.lib")
#pragma comment(lib, "avcodec-lgpl.lib")
#pragma comment(lib, "avdevice-lgpl.lib")
#pragma comment(lib, "avfilter-lgpl.lib")
#pragma comment(lib, "avformat-lgpl.lib")
#pragma comment(lib, "avutil-lgpl.lib")
#pragma comment(lib, "bz2.lib")
#pragma comment(lib, "cairo.lib")
#pragma comment(lib, "celt0.lib")
#pragma comment(lib, "croco-0.6.lib")
#pragma comment(lib, "expat.lib")
#pragma comment(lib, "flac.lib")
#pragma comment(lib, "fontconfig.lib")
#pragma comment(lib, "freetype.lib")
#pragma comment(lib, "gailutil.lib")
#pragma comment(lib, "gcrypt.lib")
#pragma comment(lib, "gdk-win32-2.0.lib")
#pragma comment(lib, "gdk_pixbuf-2.0.lib")
#pragma comment(lib, "gio-2.0.lib")
#pragma comment(lib, "glew32.lib")
#pragma comment(lib, "glib-2.0.lib")
#pragma comment(lib, "gmodule-2.0.lib")
#pragma comment(lib, "gnutls-extra.lib")
#pragma comment(lib, "gnutls-openssl.lib")
#pragma comment(lib, "gnutls.lib")
#pragma comment(lib, "gobject-2.0.lib")
#pragma comment(lib, "gpg-error.lib")
#pragma comment(lib, "gsf-1.lib")
#pragma comment(lib, "gsf-win32-1.lib")
#pragma comment(lib, "gstapp-0.10.lib")
#pragma comment(lib, "gstaudio-0.10.lib")
#pragma comment(lib, "gstbase-0.10.lib")
#pragma comment(lib, "gstbasevideo-0.10.lib")
#pragma comment(lib, "gstcdda-0.10.lib")
#pragma comment(lib, "gstcontroller-0.10.lib")
#pragma comment(lib, "gstdataprotocol-0.10.lib")
#pragma comment(lib, "gstfarsight-0.10.lib")
#pragma comment(lib, "gstfft-0.10.lib")
#pragma comment(lib, "gstgl-0.10.lib")
#pragma comment(lib, "gstinterfaces-0.10.lib")
#pragma comment(lib, "gstnet-0.10.lib")
#pragma comment(lib, "gstnetbuffer-0.10.lib")
#pragma comment(lib, "gstpbutils-0.10.lib")
#pragma comment(lib, "gstphotography-0.10.lib")
#pragma comment(lib, "gstreamer-0.10.lib")
#pragma comment(lib, "gstriff-0.10.lib")
#pragma comment(lib, "gstrtp-0.10.lib")
#pragma comment(lib, "gstrtsp-0.10.lib")
#pragma comment(lib, "gstsdp-0.10.lib")
#pragma comment(lib, "gstsignalprocessor-0.10.lib")
#pragma comment(lib, "gsttag-0.10.lib")
#pragma comment(lib, "gstvideo-0.10.lib")
#pragma comment(lib, "gthread-2.0.lib")
#pragma comment(lib, "gtk-win32-2.0.lib")
#pragma comment(lib, "gtkgl-2.0.lib")
#pragma comment(lib, "iconv.lib")
#pragma comment(lib, "intl.lib")
#pragma comment(lib, "jpeg.lib")
#pragma comment(lib, "mms.lib")
#pragma comment(lib, "mp3lame.lib")
#pragma comment(lib, "neon.lib")
#pragma comment(lib, "nice.lib")
#pragma comment(lib, "ogg.lib")
#pragma comment(lib, "oil-0.3.lib")
#pragma comment(lib, "openjpeg.lib")
#pragma comment(lib, "orc-0.4.lib")
#pragma comment(lib, "orc-float-0.4.lib")
#pragma comment(lib, "orc-test-0.4.lib")
#pragma comment(lib, "pango-1.0.lib")
#pragma comment(lib, "pangocairo-1.0.lib")
#pragma comment(lib, "pangoft2-1.0.lib")
#pragma comment(lib, "pangowin32-1.0.lib")
#pragma comment(lib, "pixman.lib")
#pragma comment(lib, "png14.lib")
#pragma comment(lib, "pthreadGC2.lib")
#pragma comment(lib, "rsvg-2.lib")
#pragma comment(lib, "schroedinger-1.0.lib")
#pragma comment(lib, "sdl.lib")
#pragma comment(lib, "soup-2.4.lib")
#pragma comment(lib, "speex.lib")
#pragma comment(lib, "speexdsp.lib")
#pragma comment(lib, "swscale-lgpl.lib")
#pragma comment(lib, "tasn1.lib")
#pragma comment(lib, "theora.lib")
#pragma comment(lib, "theoradec.lib")
#pragma comment(lib, "theoraenc.lib")
#pragma comment(lib, "tiff.lib")
#pragma comment(lib, "vorbis.lib")
#pragma comment(lib, "vorbisenc.lib")
#pragma comment(lib, "vorbisfile.lib")
#pragma comment(lib, "wavpack.lib")
#pragma comment(lib, "xml2.lib")
#pragma comment(lib, "z.lib")

#elif NDEBUG
#pragma comment(lib, "WPGStreamer.lib")

#pragma comment(lib, "atk-1.0.lib")
#pragma comment(lib, "avcodec-lgpl.lib")
#pragma comment(lib, "avdevice-lgpl.lib")
#pragma comment(lib, "avfilter-lgpl.lib")
#pragma comment(lib, "avformat-lgpl.lib")
#pragma comment(lib, "avutil-lgpl.lib")
#pragma comment(lib, "bz2.lib")
#pragma comment(lib, "cairo.lib")
#pragma comment(lib, "celt0.lib")
#pragma comment(lib, "croco-0.6.lib")
#pragma comment(lib, "expat.lib")
#pragma comment(lib, "flac.lib")
#pragma comment(lib, "fontconfig.lib")
#pragma comment(lib, "freetype.lib")
#pragma comment(lib, "gailutil.lib")
#pragma comment(lib, "gcrypt.lib")
#pragma comment(lib, "gdk-win32-2.0.lib")
#pragma comment(lib, "gdk_pixbuf-2.0.lib")
#pragma comment(lib, "gio-2.0.lib")
#pragma comment(lib, "glew32.lib")
#pragma comment(lib, "glib-2.0.lib")
#pragma comment(lib, "gmodule-2.0.lib")
#pragma comment(lib, "gnutls-extra.lib")
#pragma comment(lib, "gnutls-openssl.lib")
#pragma comment(lib, "gnutls.lib")
#pragma comment(lib, "gobject-2.0.lib")
#pragma comment(lib, "gpg-error.lib")
#pragma comment(lib, "gsf-1.lib")
#pragma comment(lib, "gsf-win32-1.lib")
#pragma comment(lib, "gstapp-0.10.lib")
#pragma comment(lib, "gstaudio-0.10.lib")
#pragma comment(lib, "gstbase-0.10.lib")
#pragma comment(lib, "gstbasevideo-0.10.lib")
#pragma comment(lib, "gstcdda-0.10.lib")
#pragma comment(lib, "gstcontroller-0.10.lib")
#pragma comment(lib, "gstdataprotocol-0.10.lib")
#pragma comment(lib, "gstfarsight-0.10.lib")
#pragma comment(lib, "gstfft-0.10.lib")
#pragma comment(lib, "gstgl-0.10.lib")
#pragma comment(lib, "gstinterfaces-0.10.lib")
#pragma comment(lib, "gstnet-0.10.lib")
#pragma comment(lib, "gstnetbuffer-0.10.lib")
#pragma comment(lib, "gstpbutils-0.10.lib")
#pragma comment(lib, "gstphotography-0.10.lib")
#pragma comment(lib, "gstreamer-0.10.lib")
#pragma comment(lib, "gstriff-0.10.lib")
#pragma comment(lib, "gstrtp-0.10.lib")
#pragma comment(lib, "gstrtsp-0.10.lib")
#pragma comment(lib, "gstsdp-0.10.lib")
#pragma comment(lib, "gstsignalprocessor-0.10.lib")
#pragma comment(lib, "gsttag-0.10.lib")
#pragma comment(lib, "gstvideo-0.10.lib")
#pragma comment(lib, "gthread-2.0.lib")
#pragma comment(lib, "gtk-win32-2.0.lib")
#pragma comment(lib, "gtkgl-2.0.lib")
#pragma comment(lib, "iconv.lib")
#pragma comment(lib, "intl.lib")
#pragma comment(lib, "jpeg.lib")
#pragma comment(lib, "mms.lib")
#pragma comment(lib, "mp3lame.lib")
#pragma comment(lib, "neon.lib")
#pragma comment(lib, "nice.lib")
#pragma comment(lib, "ogg.lib")
#pragma comment(lib, "oil-0.3.lib")
#pragma comment(lib, "openjpeg.lib")
#pragma comment(lib, "orc-0.4.lib")
#pragma comment(lib, "orc-float-0.4.lib")
#pragma comment(lib, "orc-test-0.4.lib")
#pragma comment(lib, "pango-1.0.lib")
#pragma comment(lib, "pangocairo-1.0.lib")
#pragma comment(lib, "pangoft2-1.0.lib")
#pragma comment(lib, "pangowin32-1.0.lib")
#pragma comment(lib, "pixman.lib")
#pragma comment(lib, "png14.lib")
#pragma comment(lib, "pthreadGC2.lib")
#pragma comment(lib, "rsvg-2.lib")
#pragma comment(lib, "schroedinger-1.0.lib")
#pragma comment(lib, "sdl.lib")
#pragma comment(lib, "soup-2.4.lib")
#pragma comment(lib, "speex.lib")
#pragma comment(lib, "speexdsp.lib")
#pragma comment(lib, "swscale-lgpl.lib")
#pragma comment(lib, "tasn1.lib")
#pragma comment(lib, "theora.lib")
#pragma comment(lib, "theoradec.lib")
#pragma comment(lib, "theoraenc.lib")
#pragma comment(lib, "tiff.lib")
#pragma comment(lib, "vorbis.lib")
#pragma comment(lib, "vorbisenc.lib")
#pragma comment(lib, "vorbisfile.lib")
#pragma comment(lib, "wavpack.lib")
#pragma comment(lib, "xml2.lib")
#pragma comment(lib, "z.lib")
#else
	#pragma comment(lib, "WPGStreamer.lib")

	#pragma comment(lib, "gstreamer-0.10.lib")
#pragma comment(lib, "gthread-2.0.lib")
#endif



#ifndef _FB_STATIC_LIB_
	#define FB_GSTREAMER_API __declspec(dllexport)
#else
	#define FB_GSTREAMER_API
#endif

#include "video\IVideoManager.hpp"

namespace fb
{



	FB_GSTREAMER_API VideoManagerPtr FBCALLCONV createGStreamerVideoManager();



} // end namespace fb



#endif // WPGStreamer_h__