# CMake generated Testfile for 
# Source directory: G:/Workphone/Tests/GraphicsProduction
# Build directory: G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(WPGraphics.production_Skinning "G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction/Debug/WPGraphicsSkinningTests.exe")
  set_tests_properties(WPGraphics.production_Skinning PROPERTIES  LABELS "graphics;headless;production" TIMEOUT "30" _BACKTRACE_TRIPLES "G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;17;add_test;G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(WPGraphics.production_Skinning "G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction/Release/WPGraphicsSkinningTests.exe")
  set_tests_properties(WPGraphics.production_Skinning PROPERTIES  LABELS "graphics;headless;production" TIMEOUT "30" _BACKTRACE_TRIPLES "G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;17;add_test;G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(WPGraphics.production_Skinning "G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction/MinSizeRel/WPGraphicsSkinningTests.exe")
  set_tests_properties(WPGraphics.production_Skinning PROPERTIES  LABELS "graphics;headless;production" TIMEOUT "30" _BACKTRACE_TRIPLES "G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;17;add_test;G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(WPGraphics.production_Skinning "G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction/RelWithDebInfo/WPGraphicsSkinningTests.exe")
  set_tests_properties(WPGraphics.production_Skinning PROPERTIES  LABELS "graphics;headless;production" TIMEOUT "30" _BACKTRACE_TRIPLES "G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;17;add_test;G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;0;")
else()
  add_test(WPGraphics.production_Skinning NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(WPGraphics.production_ParticleSimulation "G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction/Debug/WPGraphicsParticleSimulationTests.exe")
  set_tests_properties(WPGraphics.production_ParticleSimulation PROPERTIES  LABELS "graphics;headless;production" TIMEOUT "30" _BACKTRACE_TRIPLES "G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;17;add_test;G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(WPGraphics.production_ParticleSimulation "G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction/Release/WPGraphicsParticleSimulationTests.exe")
  set_tests_properties(WPGraphics.production_ParticleSimulation PROPERTIES  LABELS "graphics;headless;production" TIMEOUT "30" _BACKTRACE_TRIPLES "G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;17;add_test;G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(WPGraphics.production_ParticleSimulation "G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction/MinSizeRel/WPGraphicsParticleSimulationTests.exe")
  set_tests_properties(WPGraphics.production_ParticleSimulation PROPERTIES  LABELS "graphics;headless;production" TIMEOUT "30" _BACKTRACE_TRIPLES "G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;17;add_test;G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(WPGraphics.production_ParticleSimulation "G:/Workphone/project_graphics_effects_tests/Tests/GraphicsProduction/RelWithDebInfo/WPGraphicsParticleSimulationTests.exe")
  set_tests_properties(WPGraphics.production_ParticleSimulation PROPERTIES  LABELS "graphics;headless;production" TIMEOUT "30" _BACKTRACE_TRIPLES "G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;17;add_test;G:/Workphone/Tests/GraphicsProduction/CMakeLists.txt;0;")
else()
  add_test(WPGraphics.production_ParticleSimulation NOT_AVAILABLE)
endif()
