set(WP_IOS_PLATFORM "OS" CACHE STRING "iOS platform: OS or SIMULATOR")
set_property(CACHE WP_IOS_PLATFORM PROPERTY STRINGS OS SIMULATOR)

set(CMAKE_SYSTEM_NAME iOS CACHE STRING "" FORCE)
set(WP_BUILD_APPLE_IOS ON CACHE BOOL "Build Apple iOS" FORCE)
set(APPLE_IOS TRUE CACHE BOOL "Build Apple iOS" FORCE)

if(WP_IOS_PLATFORM STREQUAL "SIMULATOR")
    set(CMAKE_OSX_SYSROOT iphonesimulator CACHE STRING "" FORCE)
    set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64" CACHE STRING "" FORCE)
else()
    set(CMAKE_OSX_SYSROOT iphoneos CACHE STRING "" FORCE)
    set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "" FORCE)
endif()

set(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "1,2" CACHE STRING "" FORCE)
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE "NO" CACHE STRING "" FORCE)
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "Apple Development" CACHE STRING "" FORCE)
set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC "YES" CACHE STRING "" FORCE)
