if(CMAKE_SYSTEM_NAME STREQUAL "iOS" OR WP_BUILD_APPLE_IOS)
    set(WP_BUILD_APPLE_IOS ON CACHE BOOL "Build Apple iOS" FORCE)
    set(APPLE_IOS TRUE CACHE BOOL "Build Apple iOS" FORCE)
endif()

if(ANDROID OR APPLE_IOS)
    set(WP_MOBILE TRUE CACHE BOOL "Build for a mobile platform" FORCE)
else()
    set(WP_MOBILE FALSE CACHE BOOL "Build for a mobile platform" FORCE)
endif()

if(WP_MOBILE)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build libraries as shared" FORCE)
    set(WP_STATIC_LIB ON CACHE BOOL "Build the engine as static libraries" FORCE)
    set(WP_STATIC_LINK_CRT ON CACHE BOOL "Build with the crt statically linked" FORCE)

    set(WP_BUILD_C OFF CACHE BOOL "Include C tools in the build" FORCE)
    set(WP_BUILD_CPP ON CACHE BOOL "Include C++ tools in the build" FORCE)
    set(WP_BUILD_CSHARP OFF CACHE BOOL "Include C# tools in the build" FORCE)

    set(WP_BUILD_SAMPLES OFF CACHE BOOL "Build samples" FORCE)
    set(WP_BUILD_TESTS OFF CACHE BOOL "Build tests" FORCE)
    set(WP_BUILD_TOOLS OFF CACHE BOOL "Build tools" FORCE)
    set(WP_BUILD_EDITOR OFF CACHE BOOL "Build editor" FORCE)
    set(WP_BUILD_WXWIDGETS OFF CACHE BOOL "Build wxwidgets" FORCE)
    set(WP_BUILD_DIRECTSHOW OFF CACHE BOOL "Build direct show" FORCE)
    set(WP_BUILD_AUDIO ON CACHE BOOL "Build audio" FORCE)
    set(WP_BUILD_FMOD OFF CACHE BOOL "Build fmod" FORCE)
    set(WP_BUILD_FILEWATCHER OFF CACHE BOOL "build file watcher" FORCE)
    set(WP_BUILD_OISINPUT OFF CACHE BOOL "Build ois" FORCE)
    set(WP_BUILD_Proprietary OFF CACHE BOOL "build proprietary" FORCE)

    set(WP_BUILD_PHYSX OFF CACHE BOOL "Build physx" FORCE)
    set(WP_BUILD_PHYSX_4 OFF CACHE BOOL "Build physx 4" FORCE)
    set(WP_BUILD_PHYSICS3 ON CACHE BOOL "Build physics" FORCE)
    set(WP_ENABLE_RAKNET OFF CACHE BOOL "Use raknet" FORCE)
    set(WP_USE_ASSET_IMPORT OFF CACHE BOOL "Use asset import" FORCE)
    set(WP_USE_FBXSDK OFF CACHE BOOL "Use fbx sdk" FORCE)
    set(WP_USE_TBB OFF CACHE BOOL "Enable tbb" FORCE)
    set(WP_USE_ONETBB OFF CACHE BOOL "Enable one tbb" FORCE)

    #set(WP_GRAPHICS_SYSTEM_CLAW OFF CACHE BOOL "Build claw" FORCE)
    #set(WP_GRAPHICS_SYSTEM_OGRE OFF CACHE BOOL "Build ogre" FORCE)
	#set(WP_GRAPHICS_SYSTEM_OGRENEXT ON CACHE BOOL "Build ogre next" FORCE)
    #set(WP_GRAPHICS_SYSTEM_SOFTWARE OFF CACHE BOOL "Build software renderer" FORCE)
    #set(WP_GRAPHICS_SYSTEM_USE_STATIC_LIBS ON CACHE BOOL "Use static libraries" FORCE)

    #set(WP_BUILD_RENDERER_DX9 OFF CACHE BOOL "Build dx9" FORCE)
    #set(WP_BUILD_RENDERER_DX11 OFF CACHE BOOL "Build dx11" FORCE)
    #set(WP_BUILD_RENDERER_OPENGL OFF CACHE BOOL "Build open gl" FORCE)
    #set(WP_BUILD_RENDERER_GL3PLUS OFF CACHE BOOL "Build open gl 3 plus" FORCE)
    #set(WP_BUILD_RENDERER_VULKAN ON CACHE BOOL "Build vulkan" FORCE)
    #set(WP_BUILD_RENDERER_METAL OFF CACHE BOOL "Build metal" FORCE)
    #set(WP_BUILD_RENDERER_GLES2 OFF CACHE BOOL "Build open gles2" FORCE)

    set(WP_USE_C_MATH ON CACHE BOOL "use c math" FORCE)
    set(WP_USE_NEON_MATH OFF CACHE BOOL "use neon math" FORCE)
    set(WP_USE_SIMD OFF CACHE BOOL "use simd" FORCE)
endif()

if(ANDROID)
    set(WP_TARGET_PLATFORM "android" CACHE STRING "Workphone target platform" FORCE)
    set(WP_TARGET_ARCH "${ANDROID_ABI}" CACHE STRING "Workphone target arch" FORCE)
elseif(APPLE_IOS)
    string(REPLACE ";" "-" _wp_ios_arch_label "${CMAKE_OSX_ARCHITECTURES}")
    set(WP_TARGET_PLATFORM "iOS" CACHE STRING "Workphone target platform" FORCE)
    set(WP_TARGET_ARCH "${_wp_ios_arch_label}" CACHE STRING "Workphone target arch" FORCE)
elseif(APPLE)
    set(WP_TARGET_PLATFORM "macOS" CACHE STRING "Workphone target platform" FORCE)
elseif(WIN32)
    set(WP_TARGET_PLATFORM "windows" CACHE STRING "Workphone target platform" FORCE)
elseif(UNIX)
    set(WP_TARGET_PLATFORM "linux" CACHE STRING "Workphone target platform" FORCE)
endif()
