#ifndef _RotateManipulator_H
#define _RotateManipulator_H

#include <Workphone/System/Manipulator.hpp>

namespace workphone
{
    /** The RotateManipulator is used to rotate objects in the scene.
     *  It is a gizmo consisting of three circles, one for each axis.
     *  The user can click and drag on the circles to rotate the object.
     *  The circles are drawn in the x-y, y-z and x-z planes.
     */
    class WPCore_API RotateManipulator : public Manipulator
    {
    public:
        /**
         * Constructor.
         * @param drawDebugLines Whether to use the engine-native debug-line gizmo.
         */
        explicit RotateManipulator( bool drawDebugLines = false );

        /** Destructor. */
        ~RotateManipulator() override;

        /** Loads the manipulator.
         *  @param data The data to load.
         */
        void load( SmartPtr<ISharedObject> data ) override;

        /** Unloads the manipulator.
         *  @param data The data to unload.
         */
        void unload( SmartPtr<ISharedObject> data ) override;

        /** Updates the manipulator.
         */
        void update() override;

        /** Handles an input event.
         *  @param event The input event to handle.
         *  @return True if the event was handled, false otherwise.
         */
        bool handleEvent( const SmartPtr<IInputEvent> &event ) override;

        /** Returns whether the engine-native debug-line gizmo is enabled. */
        bool getDrawDebugLines() const;

        /** Enables or disables the engine-native debug-line gizmo. */
        void setDrawDebugLines( bool drawDebugLines );

        WP_CLASS_REGISTER_DECL;

    private:
        /** Shows or hides all engine-native debug circles owned by this manipulator. */
        void setDebugCirclesVisible( bool visible );

        // the axis around which the translatation takes place
        Vector3<real_Num> vAxis;

        // The start position of the gizmo's movement
        Vector3<real_Num> m_vStart;

        // The current position of the gizmo's movement
        Vector3<real_Num> m_intersectionPoint;

        // The current position of the gizmo's movement
        Vector2<real_Num> m_prevCursor;

        // The current position of the gizmo's movement
        Vector2<real_Num> m_cursorPos;

        // The tolerance for the intersection test
        f32 m_tollerance = 0.2f;

        // The width of the control circles
        f32 m_controlWidth = 0.05f;

        // Controls the size of the circles
        f32 m_cameraDistanceScale = 0.2f;

        // Rotation in degrees generated by one pixel of mouse movement.
        f32 m_rotationSpeed = 0.5f;

        // Whether a drag of one of the rotation circles is active.
        bool m_mouseButtonDown = false;

        // Whether to render and interact with the engine-native debug-line gizmo.
        bool m_drawDebugLines = false;

        // The control circles
        Array<SmartPtr<render::IDebugCircle>> m_circles;

        // The control circles orientations
        Array<Quaternion<real_Num>> m_orientations;

        // To know which control circles are selected
        Array<bool> m_selected;
    };
}  // namespace workphone

#endif
