#ifndef Handle_h__
#define Handle_h__

#include <Workphone/WorkphonePrerequisites.hpp>
#include <Workphone/Core/StringTypes.hpp>
#include <Workphone/Core/UUID.hpp>
#include <Workphone/Atomics/AtomicTypes.hpp>
#include <Workphone/Thread/SpinRWMutex.hpp>

namespace workphone
{

    /**
     * Used to reference objects.
     */
    class WPCore_API Handle
    {
    public:
        /** Constructs a new Handle with default values. */
        Handle();

        /** Constructs a new Handle by copying another handle.
         *  @param other: The handle to be copied.
         */
        Handle( const Handle &other );

        /** Destroys this handle. */
        ~Handle();

        /** Returns the hash value of the handle name.
         *  @return The hash value of the handle name.
         */
        hash64 getHash() const;

        /** Sets the hash value of the handle name.
         *  @param hash: The hash value to set.
         */
        void setHash( hash64 hash );

        /** Returns the hash value as unsigned int (with truncation if needed).
         *  @return The hash value as unsigned int.
         */
        u32 getHashAsUInt() const;

        /** Returns the UUID of the handle.
         *  @return The UUID of the handle.
         */
        String getUUIDAsString() const;

        /** Returns the UUID of the handle.
         *  @return The UUID of the handle.
         */
        UUID getUUID() const;

        /** Sets the UUID of the handle.
         *  @param uuid: The UUID to set.
         */
        void setUUID( const String &uuid );

        /** Sets the UUID of the handle.
         *  @param uuid: The UUID to set.
         */
        void setUUID( const UUID &uuid );

        /** Returns the ID of the handle.
         *  @return The ID of the handle.
         */
        hash_type getId() const;

        /** Returns the ID as u32 (with truncation if needed).
         *  @return The ID as u32.
         */
        u32 getIdAsUInt() const;

        /** Sets the ID of the handle.
         *  @param id The ID to set.
         */
        void setId( hash_type id );

        /** Sets the ID from u32 (with extension if needed).
         *  @param id The ID to set.
         */
        void setIdFromUInt( u32 id );

        /** Returns the instance ID of the handle.
         *  @return The instance ID of the handle.
         */
        u32 getInstanceId() const;

        /** Sets the instance ID of the handle.
         *  @param instanceId The instance ID to set.
         */
        void setInstanceId( u32 instanceId );

        /** Checks whether two handles are equal.
         *  @param b: The handle to compare with.
         *  @return True if the handles are equal, false otherwise.
         */
        bool operator==( const Handle &b );

        /** Assigns the value of another handle to this handle.
         *  @param other: The handle to be assigned.
         *  @return A reference to this handle.
         */
        Handle &operator=( const Handle &other );

        /** Returns a string representation of the handle.
         *  @return A string representation of the handle.
         */
        String toString() const;

        /** Returns the class UUID of the handle.
         *  @return The class UUID.
         */
        UUID getClassId() const;

        /** Sets the class UUID of the handle.
         *  @param classId The class UUID to set.
         */
        void setClassId( const UUID &classId );

        /** Returns the file UUID of the handle.
         *  @return The file UUID.
         */
        UUID getFileId() const;

        /** Sets the file UUID of the handle.
         *  @param fileId The file UUID to set.
         */
        void setFileId( const UUID &fileId );

    private:
        /** The UUID of the handle. */
        UUID m_uuid;

        /** The class UUID of the handle. */
        UUID m_classId;

        /** The file UUID of the handle. */
        UUID m_fileId;

        /** The hash value of the handle name. */
        atomic_s64 m_hash = std::numeric_limits<hash64>::max();

        /** The ID of the handle. */
        atomic_s64 m_id = std::numeric_limits<hash64>::max();

        /** The ID of the handle that is incremented based on the object type. */
        atomic_u32 m_instanceId = std::numeric_limits<u32>::max();

        /** The mutex used to lock the handle. */
        mutable SpinRWMutex m_mutex;

        /** The extension to use for autogenerated names. */
        static u32 m_idExt;
    };

    inline u32 Handle::getInstanceId() const
    {
        return m_instanceId;
    }

    inline u32 Handle::getHashAsUInt() const
    {
        return static_cast<u32>( m_hash );
    }

    inline u32 Handle::getIdAsUInt() const
    {
        return static_cast<u32>( m_id );
    }

    inline void Handle::setIdFromUInt( u32 id )
    {
        m_id = static_cast<hash64>( id );
    }

}  // namespace workphone

#endif  // Handle_h__
