//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
    
    private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
    
    public static Settings Default {
        get {
            return defaultInstance;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
    public string FBDatabasePath {
        get {
            return ((string)(this["FBDatabasePath"]));
        }
        set {
            this["FBDatabasePath"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
    public string Airfoil {
        get {
            return ((string)(this["Airfoil"]));
        }
        set {
            this["Airfoil"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
    public string CacheModelData {
        get {
            return ((string)(this["CacheModelData"]));
        }
        set {
            this["CacheModelData"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
    public string FoilData {
        get {
            return ((string)(this["FoilData"]));
        }
        set {
            this["FoilData"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
    public string Setting {
        get {
            return ((string)(this["Setting"]));
        }
        set {
            this["Setting"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string FBDatabaseOtherDB {
        get {
            return ((string)(this["FBDatabaseOtherDB"]));
        }
        set {
            this["FBDatabaseOtherDB"] = value;
        }
    }
    
    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("")]
    public string ModelImport {
        get {
            return ((string)(this["ModelImport"]));
        }
        set {
            this["ModelImport"] = value;
        }
    }
}
